Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-07, with the labels that each got.

#5720 chore: refactor code to use the pointer package
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/collector.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/statefulset.go
Labels: size/M

#5726 refactor: improve prometheus package function
  pkg/operator/gzip_config.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/statefulset.go
  pkg/prometheus/store.go
Labels: size/M

#5727 alertmanager: add etc/alertmanager/config
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  test/e2e/alertmanager_test.go
  test/e2e/main_test.go
Labels: size/M

#5671 Discord integration
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/discordconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/receiver.go
  pkg/client/applyconfiguration/monitoring/v1beta1/discordconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/receiver.go
  pkg/client/applyconfiguration/utils.go
Labels: size/XXL

#5723 docs: Improve Thanos Ruler doc with examples
  Documentation/thanos.md
Labels: size/S

#5675 feat: Add support to do kubernetes node monitoring
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/kubernetessdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/L

#5729 RELEASE.md: add simonpasquier for 0.67
  RELEASE.md
Labels: size/XS

#5743 Update github.com/thanos-io/thanos
  go.mod
  go.sum
Labels: size/XS

#5709 feat: Adding Consul support to ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
Labels: size/XXL

#5646 feat: update Prometheus to v2.45.0 & Add global limits fields
  Documentation/api.md
  Documentation/compatibility.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/operator/defaults.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/L

#5767 chore: bump k8s.io/client-go to v0.27.4
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/S

#5768 jsonnet/prometheus-operator: expose resource settings for the reloader
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
Labels: size/S

#5770 chore: use generics for stringMapToMapSlice()
  pkg/prometheus/promcfg.go
Labels: size/S

#5750 pkg/apis: Add params to ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/M

#5774 chore: cut v0.67.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
Labels: size/M

#5775 chore: bump prometheus-operator in go.mod files
  go.mod
  pkg/client/go.mod
Labels: size/XS

#5769 chore: refactor reloader arguments
  Documentation/operator.md
  cmd/operator/main.go
  pkg/operator/config.go
  pkg/operator/config_reloader.go
  pkg/operator/config_reloader_test.go
  pkg/operator/config_reloader_test_lib.go
Labels: size/L
