Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-10, with the labels that each got.

#5954 fixes race condition when deleting alertmanager, prometheus and thanosruler instances
  pkg/alertmanager/operator.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/S

#5955 docs: improve alertmanagerConfig description
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
Labels: size/S

#5963 Enable depguard in more packages
  .golangci.yml
  pkg/assets/store.go
  pkg/informers/informers.go
Labels: size/M

#5968 Add @nicolastakashi to Triage members list
  MAINTAINERS.md
Labels: size/XS

#5969 Enable depguard in more packages
  .golangci.yml
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/labels.go
  pkg/k8sutil/merge.go
  pkg/namespacelabeler/labeler.go
  pkg/operator/resource_reconciler.go
  pkg/operator/rules.go
  pkg/operator/sharded_secret.go
Labels: size/M

#5886 feat: support `user_key_file` and `token_file` to the pushover
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/alertmanager/validation/v1beta1/validation_test.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/pushoverconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/pushoverconfig.go
Labels: size/L

#5975 *: changing @paulfantom company affiliation and adding as 0.70 release shepherd
  MAINTAINERS.md
  RELEASE.md
Labels: size/XS

#5979 docs: Update xiu's affiliation
  MAINTAINERS.md
Labels: size/S

#5986 chore: add Simon as 0.69 shepherd
  RELEASE.md
Labels: size/XS

#5973 Enable depguard in prometheus pkg
  .golangci.yml
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/rules.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/statefulset.go
  pkg/prometheus/store.go
Labels: size/L

#5981 fix: set verbosity log level only for debug
  cmd/operator/main.go
  internal/log/log.go
Labels: size/S

#5985 change: consider nil optional to be false for additional configs
  pkg/k8sutil/secrets.go
  pkg/k8sutil/secrets_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
Labels: size/L

#5984 Enable depguard in more packages
  .golangci.yml
  pkg/thanos/operator.go
  pkg/thanos/rules.go
  pkg/thanos/statefulset.go
Labels: size/M

#5982 fix: use metadata informer for agent controller
  pkg/prometheus/agent/operator.go
Labels: size/M

#5999 chore: update Prometheus version to v2.47.1
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/operator/defaults.go
Labels: size/S

#5990 Enable depguard in e2e tests
  .golangci.yml
  test/e2e/alertmanager_test.go
  test/e2e/denylist_test.go
  test/e2e/prometheus_instance_namespaces_test.go
  test/e2e/prometheus_test.go
Labels: size/L

#5983 test(e2e-alertmanager): add alertmanager e2e test
  test/e2e/alertmanager_test.go
  test/e2e/main_test.go
Labels: size/L

#6005 chore: fix e2e tests compilation
  test/e2e/alertmanager_test.go
Labels: size/XS

#6008 fix: do not strip essential fields
  Makefile
Labels: size/XS

#6014 chore: bump k8s dependencies to 0.28.2
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#6024 change: drop deprecated metrics
  cmd/operator/main.go
  pkg/admission/admission.go
  pkg/admission/admission_test.go
Labels: size/M

#6029 chore: bump k8s dependencies to 0.28.3
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#5971 fix: update reloader requests and limits when updated
  pkg/operator/config.go
  test/e2e/config_reloader_test.go
  test/e2e/main_test.go
  test/framework/framework.go
  test/framework/role_binding.go
Labels: size/L

#6012 feat: add support for RoleARN and Filters in EC2SDConfigs
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ec2filter.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ec2sdconfig.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigFilters.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValidAPIKeys.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValidRoleARN.golden
Labels: size/M

#6002 feat: adding alertmanager msteams support
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/testdata/CR_with_MSTeams_Receiver.golden
  pkg/alertmanager/types.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/msteamsconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/receiver.go
  pkg/client/applyconfiguration/monitoring/v1beta1/msteamsconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/receiver.go
  pkg/client/applyconfiguration/utils.go
Labels: size/XXL

#6028 fix: disable HTTP2 connections by default
  Documentation/operator.md
  cmd/admission-webhook/main.go
  cmd/operator/main.go
Labels: size/M

#6036 prometheus: Add AWS sigv4 auth to Alertmanager endpoints
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
  pkg/prometheus/testdata/AlertmanagerSigv4_Invalid_Prom_Version.golden
  pkg/prometheus/testdata/AlertmanagerSigv4_Valid_Prom_Version.golden
Labels: size/L

#6043 Enable depguard in more test files
  .golangci.yml
  test/framework/admission_webhooks.go
  test/framework/alertmanager.go
  test/framework/crd.go
  test/framework/framework.go
Labels: size/L

#6039 docs: Add node to auth mode when running minikube e2e tests
  README.md
Labels: size/XS

#6050 enhancement: include operator version in CRD annotations
  Makefile
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  scripts/generate/append-operator-version.sh
Labels: size/M
