Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-06, with the labels that each got.

#5698 chore: update to Kubernetes v1.27.3
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/S

#5680 chore: update e2e tests to Kubernetes v1.27.3
  .github/env
  pkg/k8sutil/k8sutil.go
  test/e2e/alertmanager_test.go
  test/e2e/kind-conf.yaml
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/thanosruler_test.go
  test/framework/helpers.go
Labels: size/S

#5677 tests: refactors probe test into generic test function
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/L

#5714 Hide generated files from Github diff
  .gitattributes
Labels: size/XS

#5710 pkg/apis: Add TLSConfig to ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/httpsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
Labels: size/L

#5658 feat: limits support for ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/M
