Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-08, with the labels that each got.

#5305 Webex Feature/API
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/types.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/receiver.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/webexconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/receiver.go
  pkg/client/applyconfiguration/monitoring/v1beta1/webexconfig.go
  pkg/client/applyconfiguration/utils.go
  test/e2e/alertmanager_test.go
Labels: size/XXL

#5788 Do not check the am version if no discord configs
  pkg/alertmanager/operator.go
Labels: size/XS

#5790 chore: cut v0.67.1
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  pkg/client/go.mod
Labels: size/M

#5791 Release 0.67
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  pkg/alertmanager/operator.go
  pkg/client/go.mod
Labels: size/M

#5776 chore: adding golden files support on webconfig tests
  .gitattributes
  CONTRIBUTING.md
  Makefile
  go.mod
  go.sum
  pkg/webconfig/config_test.go
  pkg/webconfig/testdata/HTTP_config_with_all_parameters.golden
  pkg/webconfig/testdata/TLS_config_with_all_parameters_from secrets.golden
  pkg/webconfig/testdata/minimal_TLS_config_with_certificate_from_configmap.golden
  pkg/webconfig/testdata/minimal_TLS_config_with_certificate_from_secret.golden
  pkg/webconfig/testdata/minimal_TLS_config_with_client_CA_from configmap.golden
  pkg/webconfig/testdata/tls_config_not_defined.golden
  scripts/update-golden-files.sh
Labels: size/L

#5659 docs: Add a user guide on ScrapeConfig
  Documentation/user-guides/scrapeconfig.md
Labels: size/L

#5784 reduce the number of reconciliations
  pkg/thanos/operator.go
Labels: size/S

#5794 doc: add hint why ServiceMonitor might not be in Service Discovery
  Documentation/troubleshooting.md
Labels: size/S

#5773 Feat: Ignore revisionHistoryLimit field in StatefulSet for Prometheus, Alertmanager& ThanosRuler
  pkg/alertmanager/operator.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/S

#5735 support sharding for probe
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/L

#5785 chore: adding golden files support on admission tests
  pkg/admission/admission_test.go
  pkg/admission/testdata/Test_happy_path_v1alpha1.golden
  pkg/admission/testdata/Test_happy_path_v1beta1.golden
  pkg/admission/testdata/Test_reject_on_duplicate_receiver_v1alpha1.golden
  pkg/admission/testdata/Test_reject_on_duplicate_receiver_v1beta1.golden
  pkg/admission/testdata/Test_reject_on_invalid_mute_time_intervals_v1alpha1.golden
  pkg/admission/testdata/Test_reject_on_invalid_receiver_v1alpha1.golden
  pkg/admission/testdata/Test_reject_on_invalid_receiver_v1beta1.golden
  pkg/admission/testdata/Test_reject_on_invalid_time_intervals_v1beta1.golden
  pkg/admission/testdata/badRulesNoAnnotations.golden
  pkg/admission/testdata/badRulesWithBooleanInAnnotations.golden
  pkg/admission/testdata/goodRulesWithAnnotations.golden
  pkg/admission/testdata/goodRulesWithExternalLabelsInAnnotations.golden
  pkg/admission/testdata/happy_path_v1alpha1_v1beta1.golden
  pkg/admission/testdata/happy_path_v1beta1_v1alpha1.golden
  pkg/admission/testdata/nonStringsInLabelsAnnotations.golden
Labels: size/XL

#5795 feat: adding golden files support on alertmanger tests
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/CR_with_Active_Time_Intervals.golden
  pkg/alertmanager/testdata/CR_with_Mute_Time_Intervals.golden
  pkg/alertmanager/testdata/CR_with_Opsgenie_Receiver.golden
  pkg/alertmanager/testdata/CR_with_Opsgenie_Team_Responder.golden
  pkg/alertmanager/testdata/CR_with_Pagerduty_Receiver.golden
  pkg/alertmanager/testdata/CR_with_SNS_Receiver_with_Access_and_Key.golden
  pkg/alertmanager/testdata/CR_with_SNS_Receiver_with_roleARN.golden
  pkg/alertmanager/testdata/CR_with_Slack_Receiver_and_global_Slack_URL.golden
  pkg/alertmanager/testdata/CR_with_Slack_Receiver_and_global_Slack_URL_File.golden
  pkg/alertmanager/testdata/CR_with_Telegram_Receiver.golden
  pkg/alertmanager/testdata/CR_with_WeChat_Receiver.golden
  pkg/alertmanager/testdata/CR_with_Webhook_Receiver_and_custom_http_config_oauth2.golden
  pkg/alertmanager/testdata/Discord_url_field.golden
  pkg/alertmanager/testdata/Global_opsgenie_api_key_file_field.golden
  pkg/alertmanager/testdata/OpsGenie_entity_and_actions_fields.golden
  pkg/alertmanager/testdata/base_with_sub_route_and_matchers_no_CRs.golden
  pkg/alertmanager/testdata/base_with_subroute_deprecated_matching_pattern_simple_CR.golden
  pkg/alertmanager/testdata/mute_time_intervals_field.golden
  pkg/alertmanager/testdata/skeleton_base,_CR_with_inhibition_rules_only.golden
  pkg/alertmanager/testdata/skeleton_base_CR_with_inhibition_rules_only_deprecated_matchers_are_converted.golden
  pkg/alertmanager/testdata/skeleton_base_CR_with_inhibition_rules_only_deprecated_matchers_not_converted.golden
  pkg/alertmanager/testdata/skeleton_base_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_simple_CR.golden
  pkg/alertmanager/testdata/skeleton_base_simple_CR_with_namespaceMatcher_disabled.golden
  pkg/alertmanager/testdata/skeleton_base_with_active_time_intervals_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_with_global_send_revolved_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_with_global_smtp_require_tls_set_to_false,_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_with_global_smtp_require_tls_set_to_true_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_with_inhibit_rules_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_with_mute_time_intervals_no_CRs.golden
  pkg/alertmanager/testdata/skeleton_base_with_sns_receiver_no_CRs.golden
Labels: size/XL

#5806 statefulset: remove redundant nil check around Labels and Annotations
  pkg/alertmanager/statefulset.go
  pkg/prometheus/statefulset.go
  pkg/thanos/statefulset.go
Labels: size/M

#5817 chore: use helm/kind-action
  .github/workflows/e2e.yaml
Labels: size/S

#5760 support mount multiple volumes
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/storagespec.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
Labels: size/XXL

#5752 fix minor issue with endpoint bearertoken
  pkg/alertmanager/operator.go
  pkg/apis/monitoring/v1/servicemonitor_types_test.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  test/e2e/prometheus_test.go
  test/framework/prometheus.go
Labels: size/M

#5824 Update k8s libraries to v0.28.0
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/M

#5826 Update k8s libs together
  .github/dependabot.yml
Labels: size/XS

#5823 Get status less frequently to avoid rate limits
  test/framework/status.go
Labels: size/XS

#5804 fix: support text-only email configs
  pkg/alertmanager/types.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  test/e2e/alertmanager_test.go
Labels: size/S

#5819 Upgrade k8s utils
  go.mod
  go.sum
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator_test.go
  pkg/alertmanager/validation/v1beta1/validation_test.go
  pkg/operator/statefulset_reporter.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/operator_test.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/e2e/scrapeconfig_test.go
  test/framework/alertmanager.go
  test/framework/framework.go
  test/framework/prometheus.go
  test/framework/thanosruler.go
Labels: size/L

#5834 Fix Alertmanager e2e tests for v0.26.0
  test/e2e/alertmanager_test.go
  test/framework/alertmanager.go
Labels: size/S

#5839 Revert "support mount multiple volumes"
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/storagespec.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
Labels: size/XXL

#5842 Fix collapsing user-guide weights
  Documentation/user-guides/scrapeconfig.md
  Documentation/user-guides/webhook.md
Labels: size/XS

#5848 chore: bump Alertmanager and Thanos versions
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#5841 fix: reject monitors with invalid relabel configs
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/XL

#5843 Auto-approve dependabot PRs
  .github/workflows/automerge-dependabot.yaml
Labels: size/XS

#5850 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#5854 Update scrapeconfig.md
  Documentation/user-guides/scrapeconfig.md
Labels: size/XS

#5805 pkg/apis: Add metric relabeling to ScrapeConfigs
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/L

#5856 fix: reject invalid ScrapeConfigs
  pkg/assets/store.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/L

#5732 Run PrometheusVersionUpgrade tests separately
  .github/workflows/e2e.yaml
  .github/workflows/test-prom-version-upgrade.yaml
  test/e2e/main_test.go
Labels: size/M

#5863 Add myself as 0.68 shepherd
  RELEASE.md
Labels: size/XS

#5864 Add git config to dependabot workflow
  .github/workflows/automerge-dependabot.yaml
Labels: size/XS

#5867 chore: add unit test with multiple AlertmanagerConfigs
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/skeleton_base_multiple_alertmanagerconfigs.golden
Labels: size/M

#5865 [CHORE] starting to add golden files to promcfg_tests
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/AlertmanagerBasicAuth_Invalid_Prom_Version.golden
  pkg/prometheus/testdata/AlertmanagerBasicAuth_Valid_Prom_Version.golden
  pkg/prometheus/testdata/AlertmanagerBearerToken.golden
  pkg/prometheus/testdata/Any_returns_an_empty_list_instead_of_the_current_namespace.golden
  pkg/prometheus/testdata/Any_takes_precedence_over_MatchNames.golden
  pkg/prometheus/testdata/IgnoreNamespaceSelectors_overrides_Any_and_MatchNames.golden
  pkg/prometheus/testdata/K8SSDConfigGenerationFirst.golden
  pkg/prometheus/testdata/K8SSDConfigGenerationTwo.golden
  pkg/prometheus/testdata/NamespaceSetCorrectlyForPodMonitor.golden
  pkg/prometheus/testdata/ProbeIngressSDConfigGeneration.golden
  pkg/prometheus/testdata/ProbeIngressSDConfigGenerationWithLabelEnforce.golden
  pkg/prometheus/testdata/ProbeIngressSDConfigGenerationWithShards.golden
  pkg/prometheus/testdata/ProbeStaticTargetsConfigGenerationWithJobName.golden
  pkg/prometheus/testdata/ProbeStaticTargetsConfigGenerationWithLabelEnforce.golden
  pkg/prometheus/testdata/ProbeStaticTargetsConfigGenerationWithoutModule.golden
  pkg/prometheus/testdata/external_label_specified.golden
  pkg/prometheus/testdata/global_settings_valid_config_v2.15.2.golden
  pkg/prometheus/testdata/invalid_scrape_timeout_specified_when_scrape_interval_specified.golden
  pkg/prometheus/testdata/namespaces_from_MatchNames_are_returned_instead_of_the_current_namespace.golden
  pkg/prometheus/testdata/query_log_file.golden
  pkg/prometheus/testdata/valid_global_config_with_label_limits.golden
  pkg/prometheus/testdata/valid_global_limits.golden
  pkg/prometheus/testdata/valid_scrape_timeout_along_with_valid_scrape_interval_specified.golden
Labels: size/XL

#5872 Add Deezer to ADOPTERS.md
  ADOPTERS.md
Labels: size/S

#5871 fix: Fix KuberenetesSDConfigs in ScrapeConfig
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/S
