Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-11, with the labels that each got.

#6053 feat: support Selectors field in kubernetes SD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/k8sselectorconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/kubernetessdconfig.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Selectors.golden
  test/e2e/scrapeconfig_test.go
Labels: size/L

#6011 feat: Add `--web-config-file` flag to the config reloader
  cmd/prometheus-config-reloader/main.go
  go.mod
  go.sum
  pkg/operator/config_reloader.go
  pkg/operator/config_reloader_test.go
Labels: size/M

#5699 docs: overriding behavior for common labels
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
Labels: size/M

#6064 fix: remove verbose logging admission-webhook
  cmd/admission-webhook/main.go
Labels: size/XS

#6062 chore: cut v0.69.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#6070 chore: fix filenames to avoid import failures
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/TSDB_config_greater_than_or_equal_to_v2.39.0.golden
  pkg/prometheus/testdata/TSDB_config_less_than_v2.39.0.golden
Labels: size/XS

#6071 chore: cut v0.69.1
  .github/workflows/checks.yaml
  .github/workflows/e2e.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/test-prom-version-upgrade.yaml
  .github/workflows/unit.yaml
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#6075 add flag to enable liveness and readiness for the config-reloader container from jsonnet
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
Labels: size/XS

#6074 Release 0.69
  .github/workflows/checks.yaml
  .github/workflows/e2e.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/test-prom-version-upgrade.yaml
  .github/workflows/unit.yaml
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/TSDB_config_greater_than_or_equal_to_v2.39.0.golden
  pkg/prometheus/testdata/TSDB_config_less_than_v2.39.0.golden
Labels: size/L

#6084 docs: fix spelling mistake
  Documentation/design.md
Labels: size/XS

#6088 chore: update tool versions in scripts/go.mod
  .github/workflows/checks.yaml
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/versioned/doc.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_alertmanager.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_podmonitor.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_probe.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheus.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheusrule.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_servicemonitor.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_thanosruler.go
  pkg/client/versioned/typed/monitoring/v1alpha1/fake/fake_alertmanagerconfig.go
  pkg/client/versioned/typed/monitoring/v1alpha1/fake/fake_prometheusagent.go
  pkg/client/versioned/typed/monitoring/v1alpha1/fake/fake_scrapeconfig.go
  pkg/client/versioned/typed/monitoring/v1beta1/fake/fake_alertmanagerconfig.go
  scripts/go.mod
  scripts/go.sum
Labels: size/XL

#5988 .github/workflows: skip unit and e2e tests for *.md file updates
  .github/workflows/e2e.yaml
  .github/workflows/unit.yaml
Labels: size/XS

#6089 feat: support remaining roles in kubernetesSD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/k8sselectorconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/kubernetessdconfig.go
  test/e2e/scrapeconfig_test.go
Labels: size/M

#5993 feat: optimize memory usage of secret/configmap informers
  bundle.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
  pkg/alertmanager/operator.go
  pkg/informers/informers.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
Labels: size/M

#6078 feat: Add support for Azure SD in ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/azuresdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid.golden
Labels: size/L

#6090 docs: update strategic merge patch documentation
  Documentation/user-guides/strategic-merge-patch.md
Labels: size/M

#6094 change: update json tags for ConsulSD configs
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
Labels: size/M

#6009 feat: add GCE SD support in ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/gcesdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValid.golden
Labels: size/L

#6095 chore: update ServiceMonitor documentation
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  test/e2e/prometheus_test.go
Labels: size/XL

#6096 Update Office Hours Meetings
  CONTRIBUTING.md
Labels: size/XS

#6099 fix(shards): Skip adding shard relabel rules automatically if already set
  pkg/prometheus/promcfg.go
  pkg/prometheus/testdata/AdditionalScrapeConfigs_one_prometheus_shard.golden
  pkg/prometheus/testdata/AdditionalScrapeConfigs_sharded prometheus.golden
  pkg/prometheus/testdata/AdditionalScrapeConfigs_unsharded_prometheus.golden
  pkg/prometheus/testdata/TestAdditionalScrapeConfigsAdditionalScrapeConfig.golden
Labels: size/S

#6098 fix: convert consul scheme to lowercase while setting prometheus config
  pkg/prometheus/promcfg.go
Labels: size/XS

#6097 chore: bump to Prometheus v2.48.0
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6104 chore: update PodMonitor documentation
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
Labels: size/L

#6103 Fully enable depguard
  cmd/po-rule-migration/main.go
  test/framework/config_map.go
  test/framework/deployment.go
  test/framework/helpers.go
  test/framework/ingress.go
  test/framework/namespace.go
  test/framework/pod.go
  test/framework/prometheus.go
  test/framework/prometheusagent.go
  test/framework/service.go
  test/framework/status.go
  test/framework/thanosruler.go
Labels: size/L

#6106 Remove depguard file filters
  .golangci.yml
Labels: size/S

#6109 fix: Check for nil in MS Teams config
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/CR_with_MSTeams_Receiver_Partial_Conf.golden
Labels: size/M

#6105 feat: add track_timestamps_staleness limit to CRDs
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/endpoint.go
  pkg/client/applyconfiguration/monitoring/v1/podmetricsendpoint.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TrackTimestampsStaleness.golden
  pkg/prometheus/testdata/SettingTrackTimestampsStalenessInPodMonitor.golden
  pkg/prometheus/testdata/SettingTrackTimestampsStalenessInServiceMonitor.golden
Labels: size/L

#6114 chore: tidy up go.{mod,sum} files
  .github/workflows/checks.yaml
  go.mod
  pkg/apis/monitoring/go.sum
Labels: size/XXL

#6116 chore: bump k8s.io/client-go to v0.28.4
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/S

#6006 fix: handle duplicate sources
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
Labels: size/L

#5479 Pushover device support
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/types.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/pushoverconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/pushoverconfig.go
Labels: size/S

#5690 feat: enable config reload via signal
  Documentation/api.md
  bundle.yaml
  cmd/prometheus-config-reloader/main.go
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/operator/config_reloader.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
  test/e2e/prometheus_test.go
Labels: size/XL

#6121 chore: create kubelet endpoints controller
  cmd/operator/main.go
  pkg/kubelet/controller.go
  pkg/kubelet/controller_test.go
  pkg/operator/config.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/operator_test.go
Labels: size/XL

#6124 scrapeConfig: Change to camelCase on scrapeConfig
  pkg/prometheus/promcfg.go
  pkg/prometheus/testdata/ConsulScrapeConfig.golden
  pkg/prometheus/testdata/ConsulScrapeConfigAuthorization.golden
  pkg/prometheus/testdata/ConsulScrapeConfigBasicAuth.golden
  pkg/prometheus/testdata/ConsulScrapeConfigOAuth.golden
  pkg/prometheus/testdata/ConsulScrapeConfigTLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Authorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_ARecord.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_SRVRecord.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigFilters.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValidAPIKeys.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValidRoleARN.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Empty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EmptyRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_FileSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValid.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HTTPSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorLabels.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorTimeStamp.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Selectors.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Limits.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_MetricPath.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyMetricRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Params.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Scheme.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeInterval.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeTimeout.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Static.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TrackTimestampsStaleness.golden
Labels: size/XS

#6119 Update stale workflow to close stale PRs
  .github/workflows/stale.yaml
Labels: size/XS

#6128 Use Prom-Op bot PAT token in dependabot workflow
  .github/workflows/automerge-dependabot.yaml
Labels: size/XS
