Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-12, with the labels that each got.

#6141 chore: remove unused validation code
  go.mod
  pkg/operator/validations.go
Labels: size/M

#6127 chore: use apiserver controller to reload certs
  go.mod
  go.sum
  pkg/server/server.go
Labels: size/L

#6001 feat(scrapeConfig): Add proxy settings support for the ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/httpsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/proxyconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HTTPSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ProxySettings.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ProxySettingsIncompatiblePrometheusVersion.golden
Labels: size/XL

#5967 Add `additionalLabels` field to TopologySpreadConstraint
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/corev1topologyspreadconstraint.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/topologyspreadconstraint.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
Labels: size/L

#6148 documentation: mention additionalArgs
  Documentation/user-guides/strategic-merge-patch.md
Labels: size/S

#6149 chore: mark deprecated fields correctly
  .golangci.yml
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/L

#6055 Paramaterize group for CRs to use prometheus operator with opentelemetry-operator
  pkg/apis/monitoring/register.go
Labels: size/XS

#6164 chore: bump to Prometheus v2.48.1
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6173 Add exception for PromOperator's twitter profile
  .mdox.validate.yaml
Labels: size/XS

#6113 chore: adding scrape classe
  Documentation/proposals/202305-scrapeclasses.md
Labels: size/L

#6168 feat: add OpenStack SD support in ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/openstacksdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigValid.golden
Labels: size/XL

#6137 chore: Adding StartupProbeTimeoutSeconds to Prometheus CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
  pkg/prometheus/statefulset_test.go
Labels: size/L

#6162 dedicated field for cluster_label
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
Labels: size/S

#6111 chore: create new bug issue template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yaml
Labels: size/L

#6181 chore: generalize usage of UpdateObject()
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/operator/factory.go
  pkg/operator/factory_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/operator.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/rules.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
  pkg/thanos/rules.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/L

#6182 chore: add simonpasquier for v0.71
  RELEASE.md
Labels: size/XS

#6184 chore: bump Kubernetes modules to v0.29.0
  Documentation/api.md
  Documentation/compatibility.md
  go.mod
  go.sum
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/e2e/prometheusagent_test.go
  test/e2e/thanosruler_test.go
Labels: size/M

#6187 chore: use ptr.To()
  pkg/alertmanager/statefulset.go
  pkg/operator/config_reloader.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/thanos/statefulset.go
Labels: size/M
