Repository prometheus-operator/prometheus-operator, pull requests merged in 2023-09, with the labels that each got.

#5866 feat: Add dns_sd_configs to ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dnssdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  test/e2e/main_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/L

#5877 Document server-side apply for CRDs
  Documentation/troubleshooting.md
Labels: size/S

#5892 chore: simplify NewUnprivilegedNamespaceListWatchFromClient()
  pkg/alertmanager/operator.go
  pkg/listwatch/listwatch.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/S

#5888 fix: apply externalLabels after reserved labels in prometheus
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/external_label_specified_along_with_reserved_labels.golden
Labels: size/M

#5895 Update dependencies before 0.68 release
  Documentation/compatibility.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/operator/defaults.go
Labels: size/XL

#5882 feat: add bot_token_file in TelegramConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/types.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/telegramconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/telegramconfig.go
Labels: size/L

#5900 test: update ScrapeConfig tests to use golden files
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ConsulScrapeConfig.golden
  pkg/prometheus/testdata/ConsulScrapeConfigAuthorization.golden
  pkg/prometheus/testdata/ConsulScrapeConfigBasicAuth.golden
  pkg/prometheus/testdata/ConsulScrapeConfigOAuth.golden
  pkg/prometheus/testdata/ConsulScrapeConfigTLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Authorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_ARecord.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_SRVRecord.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Empty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EmptyRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_FileSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HTTPSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorLabels.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorTimeStamp.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Limits.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_MetricPath.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyMetricRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Params.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Scheme.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeInterval.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeTimeout.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Static.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TLSConfig.golden
Labels: size/L

#5896 Prepare 0.68 release
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  pkg/client/go.mod
Labels: size/M

#5901 chore: update to Go 1.21
  .github/env
  go.mod
  go.sum
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#5876 alertmanager: add missing types
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/types.go
Labels: size/L

#5906 feat: add `--as` CLI argument
  Documentation/operator.md
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/k8sutil/k8sutil.go
  pkg/operator/config.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  scripts/run-external.sh
Labels: size/M

#5883 enhancement: Replace UpdateStatus() for ApplyStatus() to avoid informer errors
  pkg/alertmanager/operator.go
Labels: size/M

#5911 Remove typo duplicate line
  pkg/alertmanager/operator.go
Labels: size/XS

#5910 chore: refactor CRD and RBAC checks
  cmd/operator/main.go
  pkg/k8sutil/k8sutil.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
Labels: size/L

#5915 Fix objec --> object typo
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
Labels: size/XS

#5913 replace UpdateStatus() for ApplyStatus ThanosRuler
  pkg/alertmanager/operator.go
  pkg/operator/operator.go
  pkg/thanos/operator.go
Labels: size/M

#5929 docs: fix very simple typo
  README.md
Labels: size/XS

#5887 Checkout branch ref on Dependabot workflows
  .github/workflows/automerge-dependabot.yaml
Labels: size/XS

#5902 feat: add ec2_sd_configs in ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ec2sdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValid.golden
Labels: size/L

#5898 fix: reconcile on namespace changes
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/listwatch_test.go
  pkg/operator/config.go
  pkg/operator/resource_reconciler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  test/e2e/alertmanager_instance_namespaces_test.go
  test/e2e/prometheus_instance_namespaces_test.go
  test/e2e/scrapeconfig_test.go
  test/framework/framework.go
Labels: size/XL

#5919 Add controller-id proposal
  Documentation/proposals/202309-controller-id.md
Labels: size/M

#5934 fix: detect changes without list/watch perms on namespaces
  pkg/alertmanager/operator.go
  pkg/listwatch/listwatch.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  test/e2e/prometheus_instance_namespaces_test.go
Labels: size/L

#5933 fix: get IMPERSONATE_USER from current environment
  scripts/run-external.sh
Labels: size/XS

#5935 chore: use leveled log instead of fmt.Fprint()
  cmd/operator/main.go
Labels: size/S

#5937 fix: Update consul validate func
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/S

#5938 fix: Update ec2 validate func
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/S

#5926 Fix prom upgrade test
  .github/workflows/test-prom-version-upgrade.yaml
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
Labels: size/S

#5852 prometheus: Add AzureAD for remote write
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/azuread.go
  pkg/client/applyconfiguration/monitoring/v1/managedidentity.go
  pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/L

#5941 add: scrapeConfigSelector check
  pkg/prometheus/server/operator.go
Labels: size/XS

#5946 Fixing #5338 | Add OCI labels in the Dockerfile
  Dockerfile
Labels: size/XS

#5945 fix: add --cluster.label to alertmanager
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
Labels: size/M

#5943 chore: don't close doc issues
  .github/workflows/stale.yaml
Labels: size/XS

#5930 Enable depguard linter against github.com/pkg/errors
  .golangci.yml
  pkg/admission/jsonpatch.go
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
Labels: size/L
