Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-06, with the labels that each got.

#6635 fix: use a separate port number for init container
  pkg/alertmanager/statefulset.go
  pkg/operator/config_reloader.go
  pkg/operator/config_reloader_test.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
Labels: size/M

#6641 chore: refactor tokens management in the assets package
  pkg/alertmanager/operator.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
  pkg/prometheus/testdata/ConsulScrapeConfigAuthorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSDConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_Authorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Authorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD_with_TLSConfig.golden
Labels: size/L

#6640 Add `mode` field in PrometheusAgent CRD
  Documentation/api.md
  Documentation/operator.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/operator/feature_gates.go
  pkg/operator/feature_gates_test.go
Labels: size/S

#6644 chore: refactor sigv4 management in the assets package
  pkg/alertmanager/operator.go
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
Labels: size/L

#6642 chore: add test-e2e-image target to Makefile
  Makefile
  TESTING.md
Labels: size/M

#6586 Add LinodeSD configuration fields to the Scrape Config CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/linodesdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LinodeSDConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LinodeSD_with_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LinodeSD_with_OAuth.golden
Labels: size/XL

#6636 Add NODE_NAME env in config reloader
  pkg/operator/config_reloader.go
  pkg/operator/config_reloader_test.go
Labels: size/M

#6655 feat: add `prometheus_operator_feature_gate_info` metric
  Documentation/operator.md
  cmd/operator/main.go
  pkg/operator/config.go
  pkg/operator/feature_gates.go
  pkg/operator/feature_gates_test.go
Labels: size/L

#6651 ScrapeConfig CRD: Add PuppetDB Service Discovery Configurations
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/puppetdbsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_PuppetDBSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_PuppetDBSD_withBasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_PuppetDBSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_PuppetDBSD_with_TLSConfig.golden
Labels: size/XL

#6658 chore: bump code-generator to v0.30.1
  Makefile
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/corev1topologyspreadconstraint.go
  pkg/client/applyconfiguration/monitoring/v1/podmonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1/probetargetingress.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/client/applyconfiguration/monitoring/v1/topologyspreadconstraint.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/client/versioned/clientset.go
  pkg/client/versioned/fake/clientset_generated.go
  pkg/client/versioned/fake/register.go
  pkg/client/versioned/scheme/register.go
  scripts/go.mod
  scripts/go.sum
Labels: size/L

#6645 chore: refactor AzureAD management in the assets package
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/assets/types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/store.go
Labels: size/L

#6659 [Enhancement] Replacing t.Fatal with testify/require package
  pkg/operator/argument_test.go
  pkg/operator/config_reloader_test_lib.go
  pkg/operator/prober_test.go
  pkg/operator/rules_test.go
Labels: size/M

#6660 ScrapeConfig CRD: Add LightSail Service Discovery Config Options
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/lightsailsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSDConfigValidAPIKeys.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSDConfigValidRoleARN.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSD_withBasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSD_with_TLSConfig.golden
Labels: size/XXL

#6679 chore: bump to k8s.io libs v0.30.2
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#6683 Replaced t.Fatal with require in Alertmanager Package
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator_test.go
  pkg/alertmanager/statefulset_test.go
  pkg/alertmanager/validation/validation_test.go
Labels: size/XL

#6680 Replacing t.fatal with require Package
  pkg/admission/admission_test.go
  pkg/assets/store_test.go
  pkg/k8sutil/k8sutil_test.go
  pkg/k8sutil/merge_test.go
  pkg/listwatch/listwatch_test.go
Labels: size/L

#6512 feat(remote): add support prometheus remote write/read ProxyConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/client/applyconfiguration/monitoring/v1/remotereadspec.go
  pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/store.go
  pkg/prometheus/testdata/RemoteReadConfig_v2.43.0_ProxyConfig.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.43.0_ProxyConfig.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.43.0_ProxyConfigWithMutiValues.golden
Labels: size/L

#6688 WIP: Refactor common test code between Prometheus Agent's StatefulSet and DaemonSet modes
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/agent/test_utils.go
Labels: size/XL

#6692 chore: update default thanos version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6696 chore: update default prometheus version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6701 Nit: Check if EnableFeatures already contains agent mode's features
  pkg/prometheus/agent/statefulset.go
Labels: size/XS

#6698 Create correct readiness/liveness probes for config-reloader when `listenLocal` is set to `true`
  pkg/operator/config_reloader.go
Labels: size/M

#6699 [CHORE] adding Nicolas as release volunteer
  RELEASE.md
Labels: size/M

#6515 Add `ttl` obj to alertmanagercfgs resource
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/types.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/pushoverconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/pushoverconfig.go
Labels: size/S

#6600 Proposal for DaemonSet deployment of Prometheus Agent
  Documentation/proposals/202405-agent-daemonset.md
Labels: size/L

#6702 chore: factorize prober code
  pkg/operator/config_reloader.go
  pkg/operator/prober.go
  pkg/operator/prober_test.go
  pkg/prometheus/statefulset.go
Labels: size/M

#6703 chore: Replace StringPtrValOrDefault with ptr.Deref
  pkg/alertmanager/statefulset.go
  pkg/operator/image.go
  pkg/operator/storageclass.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
Labels: size/M

#6662 chore: refactor TLS management in the assets package
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/operator.go
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/assets/tls.go
  pkg/assets/types.go
  pkg/assets/utils.go
  pkg/operator/sharded_secret.go
  pkg/operator/sharded_secret_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/testdata/ConsulScrapeConfigTLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSDConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerswarmSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LightSailSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LinodeSDConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_LinodeSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_PuppetDBSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TLSConfig.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfig.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfigMissingCA.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfig.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfigMissingCA.golden
  pkg/thanos/operator.go
Labels: size/XL

#6686 Refactor the common implementation code (not including tests) between Prometheus's modes
  pkg/operator/image.go
  pkg/prometheus/agent/common.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/common.go
  pkg/prometheus/common_test.go
  pkg/prometheus/server/statefulset.go
Labels: size/L

#6694 Continue #6688: Refactor common test code between Prometheus modes
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/agent/test_utils.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/test_utils.go
Labels: size/L

#6700 chore: optimize get secret key from store
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
Labels: size/L

#6689 feat(xds): Add OVHcloud service discovery to the ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ovhcloudsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OVHCloudSD.golden
Labels: size/L

#6707 chore: bump go dependencies before release
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#6709 chore: cut 0.75.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#6710 chore: refactor annotation propagation
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/operator/factory.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/common.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/thanos/operator.go
  pkg/thanos/statefulset.go
Labels: size/L

#6685 Adding CRDs description from Design.md
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
Labels: size/M

#6549 Only add node IPs to kubelet endpoint if they have a known Ready condition
  pkg/kubelet/controller.go
  pkg/kubelet/controller_test.go
Labels: size/L

#6661 ScrapeConfig CRD: refactor `Filter` types
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dockerfilter.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dockersdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dockerswarmfilter.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dockerswarmsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ec2sdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/filter.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSDConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerswarmSD.golden
Labels: size/L

#6716 feat: pass feature gates to scripts/run-external.sh
  scripts/run-external.sh
Labels: size/XS

#6693 Adding CRD Description from Design.md to api.md for metrics-based resources
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/prometheusrule_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
Labels: size/M
