Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-05, with the labels that each got.

#6557 chore: refactor OAuth2 in the assets package
  pkg/alertmanager/operator.go
  pkg/assets/interface.go
  pkg/assets/store.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/store.go
Labels: size/XL

#6564 chore: add link to public calendar
  CONTRIBUTING.md
Labels: size/XS

#6509 Add testing steps for podman with kind
  TESTING.md
Labels: size/M

#6378 chore: Template string allowed for Responder.Type (#4882)
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  pkg/alertmanager/validation/v1beta1/validation_test.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/validation_test.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/validation_test.go
Labels: size/L

#6565 chore: update default prometheus version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6568 chore: make TLSConfig fields optional
  Documentation/api.md
  pkg/alertmanager/amcfg.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ConsulScrapeConfigTLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSDConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TLSConfig.golden
  pkg/prometheus/testdata/monitorObjectWithDefaultScrapeClassAndTLSConfig.golden
  pkg/prometheus/testdata/monitorObjectWithNonDefaultScrapeClassAndTLSConfig.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfig.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfigMissingCA.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfig.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfigMissingCA.golden
  test/e2e/prometheus_test.go
  test/e2e/scrapeconfig_test.go
  test/framework/prometheus.go
Labels: size/M

#6574 chore: update default thanos version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6582 fix: deref nil pointer on WebexConfig
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
Labels: size/XS

#6573 fix: apply TLS scrape class to all objects
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/monitorObjectWithDefaultScrapeClassAndTLSConfig.golden
  pkg/prometheus/testdata/monitorObjectWithNonDefaultScrapeClassAndTLSConfig.golden
Labels: size/L

#6581 feat: add `go_sync_mutex_wait_total_seconds_total` metric
  cmd/operator/main.go
Labels: size/XS

#6587 chore: update kind version to v0.23.0
  .github/env
Labels: size/XS

#6588 chore: update Prometheus to v2.52.0
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6467 Feat: Add `relabel_configs` field to AlertmanagerEndpoints
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
  pkg/prometheus/testdata/Alertmanager_with_RelabelConfigs.golden
Labels: size/L

#6597 chore: Update vulnerable dependency golang.org/x/net
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#6576 feat(env): auto set GOMAXPROCS by go.uber.org/automaxprocs
  cmd/operator/main.go
  cmd/prometheus-config-reloader/main.go
  go.mod
  go.sum
Labels: size/S

#6598 chore: bump k8s libraries
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#6595 feat: support SDK auth in AzureSD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/M

#6596 feat: support SDK auth in AzureAD RemoteWrite
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/azuread.go
  pkg/client/applyconfiguration/monitoring/v1/azuresdk.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/operator.go
  pkg/prometheus/operator_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/RemoteWriteConfigAzureADSDK_v2.51.0.golden
  pkg/prometheus/testdata/RemoteWriteConfigAzureADSDK_v2.52.0.golden
Labels: size/L

#6491 Add structure for feature flags
  Documentation/operator.md
  cmd/operator/main.go
  pkg/operator/feature_gates.go
Labels: size/M

#6450 [WIP] Feat: Add `alert_relabel_configs` to the Prometheus and PrometheusAgent CRD's
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/AlertmangerAlertRelabel_Invalid_Version.golden
  pkg/prometheus/testdata/AlertmangerAlertRelabel_Valid_Version.golden
Labels: size/L

#6602 chore: cut v0.74.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#6605 Corrected Documentation for xxxMonitorNamespaceSelector
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
Labels: size/S

#6607 Reload alert manager when notification templates change
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
Labels: size/M

#6427 crd: add support for source pagerduty_config option in AlertMananger CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/pagerdutyconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/pagerdutyconfig.go
Labels: size/M

#6599 feat: add automatic GOMAXPROCS to admission webhook
  cmd/admission-webhook/main.go
  cmd/operator/main.go
  cmd/prometheus-config-reloader/main.go
  internal/goruntime/cpu.go
Labels: size/M

#6480 chore: Move AlertmanagerEndpoints validation to pkg/prometheus/server
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
Labels: size/L

#6613 bugfix: Fix bug created from race conditions during merge
  pkg/prometheus/promcfg.go
Labels: size/XS

#6620 Use functional options pattern for Prometheus Controller
  cmd/operator/main.go
  pkg/prometheus/server/operator.go
Labels: size/M

#6630 chore: fix testScrapeConfigKubernetesNodeRole()
  .github/workflows/e2e.yaml
  test/e2e/scrapeconfig_test.go
  test/framework/framework.go
  test/framework/node.go
Labels: size/M

#6627 chore: add test for AlertmanagerConfig with subroutes
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/skeleton_base_CR_with_subroutes.golden
Labels: size/M

#6629 chore: bump k8s dependencies for api
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/XXL

#6623 [CHANGE] allowing kubeconfig as parameter
  cmd/operator/main.go
  pkg/k8sutil/k8sutil.go
Labels: size/M

#6618 Feat: Add JobName to ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_WithJobName.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_WithJobNameAndRelabelConfig.golden
Labels: size/M

#6626 Add feature gate for Prometheus Agent's DaemonSet deployment
  Documentation/operator.md
  cmd/operator/main.go
  pkg/operator/feature_gates.go
Labels: size/S

#6621 e2e/framework: Allow setting feature-gates when creating Prometheus-Operator
  test/framework/framework.go
Labels: size/S

#6591 feat(env): Add automatic memory limit handling
  Documentation/operator.md
  cmd/admission-webhook/main.go
  cmd/operator/main.go
  cmd/prometheus-config-reloader/main.go
  go.mod
  go.sum
  internal/goruntime/memory.go
  pkg/operator/feature_gates_test.go
Labels: size/L
