Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-11, with the labels that each got.

#7064 chore: Update controller-tools to v0.16.5
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/types.go
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7067 fix: pass GOARCH variable to the build stage
  Dockerfile
  cmd/admission-webhook/Dockerfile
  cmd/prometheus-config-reloader/Dockerfile
Labels: size/XS

#7068 Cut 0.78.1
  .github/workflows/publish.yaml
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
Labels: size/M

#7072 chore: update version in go.mod files
  go.mod
  pkg/client/go.mod
Labels: size/XS

#7069 chore: add v3.0.0-rc.0 to experimental versions
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7070 chore: fix actions for operator upgrade and typo fix
  .github/workflows/checks.yaml
  .github/workflows/e2e-prometheus3.yaml
Labels: size/XS

#7055 chore: fix TestPrometheusVersionUpgrade
  .github/workflows/test-prom-version-upgrade.yaml
  Documentation/compatibility.md
  pkg/operator/defaults.go
  test/e2e/prometheus_test.go
Labels: size/L

#7063 chore: fix gen-crd-api-reference-docs warning
  Documentation/api.md
  scripts/docs/config.json
Labels: size/XS

#7073 chore: optimize build layers
  Dockerfile
  cmd/admission-webhook/Dockerfile
  cmd/prometheus-config-reloader/Dockerfile
Labels: size/S

#7080 chore: update prometheus version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7082 ci: Let github runner run only in the prometheus-operator main repository
  .github/workflows/e2e-prometheus3.yaml
  .github/workflows/stale.yaml
  .github/workflows/test-prom-version-upgrade.yaml
Labels: size/XS

#6955 enhancement: allow toggling custom config deprecation behaviour
  Documentation/operator.md
  cmd/operator/main.go
  pkg/prometheus/server/operator.go
Labels: size/M

#7084 alertmanager: Publish non ready endpoints
  pkg/alertmanager/statefulset.go
Labels: size/XS

#7081 chore: Optimize go runtime metrics
  cmd/admission-webhook/main.go
  cmd/operator/main.go
  cmd/prometheus-config-reloader/main.go
  internal/metrics/metrics.go
Labels: size/M

#7093 fix: fix if conditions in GitHub workflows
  .github/workflows/e2e-prometheus3.yaml
  .github/workflows/stale.yaml
  .github/workflows/test-prom-version-upgrade.yaml
Labels: size/XS

#7103 chore: fix unit tests
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EnableHTTP2_False.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EnableHTTP2_True.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EnableHTTP2_Unsupported.golden
Labels: size/XS

#7006 Refactor Digital Ocean Service Discovery
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/digitaloceansdconfig.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD.golden
  test/e2e/scrapeconfig_test.go
Labels: size/L

#7102 [feat] - AM API Version Compatibility
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/AlertmanagerAPIVersionV1.golden
  pkg/prometheus/testdata/AlertmanagerAPIVersionV1PrometheusV3.golden
Labels: size/L

#6738 Refactor Consul SD Configurations
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ConsulScrapeConfig.golden
  pkg/prometheus/testdata/ConsulScrapeConfigNamespace.golden
  pkg/prometheus/testdata/ConsulScrapeConfigNamespace_unsupported_version.golden
  pkg/prometheus/testdata/ConsulScrapeConfigPathPrefix.golden
  pkg/prometheus/testdata/ConsulScrapeConfigPathPrefix_unsupported_version.golden
  test/e2e/scrapeconfig_test.go
Labels: size/XL

#7109 chore: add slashpai as release shepherd for v0.79
  RELEASE.md
Labels: size/XS

#7104 FEAT - Rename scrape_classic_histograms
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ConsulScrapeConfigNamespace.golden
  pkg/prometheus/testdata/ConsulScrapeConfigNamespace_unsupported_version.golden
  pkg/prometheus/testdata/ConsulScrapeConfigPathPrefix.golden
  pkg/prometheus/testdata/ConsulScrapeConfigPathPrefix_unsupported_version.golden
  pkg/prometheus/testdata/NativeHistogramConfigAlwaysScrapeClassicHistograms.golden
Labels: size/S, prometheus-3.0

#7111 chore: add v3.0.0 to experimental versions
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7121 chore: improve ThanosRuler documentation
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/thanos/rules.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/L

#7125 chore: update Thanos Ruler example
  example/thanos/prometheus.yaml
  example/thanos/query-deployment.yaml
  example/thanos/thanos-ruler-secret.yaml
  example/thanos/thanos-ruler.yaml
  jsonnet/thanos/config.libsonnet
  scripts/generate/thanos.jsonnet
Labels: size/M

#7116 [FEAT] - Add metric_name_validation_scheme
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/NameValidationSchemeLegacyWithPrometheusLowerThanV3.golden
  pkg/prometheus/testdata/NameValidationSchemeLegacyWithPrometheusV3.golden
  pkg/prometheus/testdata/NameValidationSchemeUTF8WithPrometheusV3.golden
  pkg/prometheus/testdata/OTLPConfig_Config_translation_strategy_with_suffixes_and_name_validation_scheme.golden
Labels: size/L

#7130 fix: revert removal of the `proxyURL` field
  CHANGELOG.md
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/httpconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/httpconfig.go
Labels: size/L

#7138 chore: fix tests
  pkg/prometheus/testdata/SettingScrapeFallbackProtocolInPodMonitor_NewVersion.golden
  pkg/prometheus/testdata/SettingScrapeFallbackProtocolInPodMonitor_OldVersion.golden
  pkg/prometheus/testdata/SettingScrapeFallbackProtocolInServiceMonitor_NewVersion.golden
  pkg/prometheus/testdata/SettingScrapeFallbackProtocolInServiceMonitor_OldVersion.golden
Labels: size/XS

#7127 Document disableCompaction defaulting when using thanos sidecar
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
Labels: size/XS

#7123 Feat: Implemented Github Action linter
  .github/workflows/actionlint.yml
  .github/workflows/changed-files.yaml
  .github/workflows/checks.yaml
  .github/workflows/e2e-feature-gated.yaml
  .github/workflows/e2e-prometheus3.yaml
  .github/workflows/e2e.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/test-prom-version-upgrade.yaml
  .github/workflows/unit.yaml
Labels: size/M

#7124 feat: Support add consul filter
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ConsulScrapeConfigWithFilter.golden
Labels: size/M

#7141 chore: bump to Kubernetes v1.31.3
  .github/env
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#7146 chore: update Thanos to v0.37.0
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/operator/defaults.go
Labels: size/M

#7118 chore: optimize AM APIVersion validation
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/AlertmanagerAPIVersionPrometheusV3.golden
  pkg/prometheus/testdata/AlertmanagerAPIVersionV1LowerCasePrometheusV3.golden
  pkg/prometheus/testdata/AlertmanagerAPIVersionV1UpperCasePrometheusV3.golden
  pkg/prometheus/testdata/AlertmanagerAPIVersionV2UpperCasePrometheusV3.golden
  test/e2e/prometheus_test.go
Labels: size/M

#7143 fix: Fix incorrect label
  Documentation/user-guides/shards-and-replicas.md
  example/shards/prometheus.yaml
Labels: size/XS

#7147 Chore: Remove outdated code from AM Statefulset generation
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
Labels: size/S

#7150 feat: Support `portNumber` in addition of port name for PodMonitor CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/podmonitor_types_test.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/podmetricsendpoint.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/podMonitorObjectWithPodName.golden
  pkg/prometheus/testdata/podMonitorObjectWithPortNumber.golden
  pkg/prometheus/testdata/podMonitorObjectWithTargetPortInt.golden
  pkg/prometheus/testdata/podMonitorObjectWithTargetPortString.golden
  test/e2e/prometheus_test.go
  test/framework/prometheus.go
Labels: size/L
