Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-02, with the labels that each got.

#6280 add slashpai to maintainers
  MAINTAINERS.md
Labels: size/XS

#6282 fix: convert `continue` field between v1alpha1 and v1beta1 AlertmanagerConfig versions
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  test/e2e/alertmanager_test.go
Labels: size/S

#6286 chore: update Kind version to v0.21.0
  .github/env
Labels: size/XS

#6274 chore: update remote-write tests
  test/e2e/prometheus_test.go
  test/e2e/scrapeconfig_test.go
  test/framework/prometheus.go
  test/framework/thanosruler.go
Labels: size/XXL

#6293 Adds WarpBuild to Adopters.md
  ADOPTERS.md
Labels: size/S

#6298 fix: don't fail metadata transform on unknown types
  pkg/informers/informers.go
  pkg/informers/informers_test.go
Labels: size/L

#6313 chore: update Kubernetes to v1.29.2
  .github/env
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/M

#6315 Update go dependencies before release
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/XXL

#6317 Update default Thanos version
  Documentation/compatibility.md
  pkg/operator/defaults.go
  pkg/operator/rules_test.go
Labels: size/XS

#6323 Update Default Prometheus version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6199 feat: adding scrape class
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/podmonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1/probespec.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/scrapeclass.go
  pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
  pkg/prometheus/testdata/monitorObjectWithDefaultScrapeClassAndTLSConfig.golden
  pkg/prometheus/testdata/monitorObjectWithNonDefaultScrapeClassAndTLSConfig.golden
  pkg/prometheus/testdata/monitorObjectWithoutScrapeClass.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfig.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfigMissingCA.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfig.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAndExistingTLSConfigMissingCA.golden
Labels: size/XXL

#6314 chore: switch example app image
  Documentation/user-guides/getting-started.md
  Documentation/user-guides/shards-and-replicas.md
  example/shards/example-app-deployment.yaml
  example/user-guides/getting-started/example-app-deployment.yaml
Labels: size/XS

#6334 fix: update kubernetes slack link
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  MAINTAINERS.md
  README.md
  contrib/kube-prometheus/README.md
Labels: size/S

#6320 docs: correct slashpai slack id
  MAINTAINERS.md
Labels: size/XS

#6321 chore: move ProxyConfig type to v1
  Documentation/api.md
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/proxyconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/digitaloceansdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/httpsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/kubernetessdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector_test.go
Labels: size/L

#6345 [FIX] scrape class regression
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/M
