Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-01, with the labels that each got.

#6185 feat: add metrics tracking status updates
  example/mixin/alerts.yaml
  jsonnet/mixin/alerts/alerts.libsonnet
  pkg/operator/resource_reconciler.go
Labels: size/M

#6191 Disable dependabot automation targeting k8s libs
  .github/workflows/automerge-dependabot.yaml
Labels: size/S

#6192 Add support for enableHttp2 in prometheus remotewrite
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/RemoteWriteConfig_v2.39.0_1.golden
Labels: size/S

#6201 chore: refactor generateScrapeConfig()
  pkg/prometheus/promcfg.go
  pkg/prometheus/testdata/ConsulScrapeConfig.golden
  pkg/prometheus/testdata/ConsulScrapeConfigAuthorization.golden
  pkg/prometheus/testdata/ConsulScrapeConfigBasicAuth.golden
  pkg/prometheus/testdata/ConsulScrapeConfigOAuth.golden
  pkg/prometheus/testdata/ConsulScrapeConfigTLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Authorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_ARecord.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_SRVRecord.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigFilters.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValidAPIKeys.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigValidRoleARN.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Empty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_FileSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValid.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HTTPSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorLabels.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorTimeStamp.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Selectors.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Limits.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_MetricPath.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyMetricRelabelConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigEmpty.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigValid.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Params.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ProxySettings.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ProxySettingsIncompatiblePrometheusVersion.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Scheme.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeInterval.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeTimeout.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Static.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_TrackTimestampsStaleness.golden
Labels: size/S

#6203 chore: fix pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
Labels: size/L

#5961 Add proposal for Shard Autoscaling
  Documentation/proposals/202310-shard-autoscaling.md
Labels: size/L

#6200 chore: refactor ShardedSecret
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/assets/types.go
  pkg/operator/factory.go
  pkg/operator/sharded_secret.go
  pkg/operator/sharded_secret_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/operator.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/operator_test.go
Labels: size/L

#5903 Add testing guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Makefile
  README.md
  TESTING.md
Labels: size/L

#6208 Ensure all comments end with a period
  .golangci.yml
  pkg/admission/admission.go
  pkg/admission/admission_test.go
  pkg/admission/admissiontypes.go
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator_test.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/alertmanager/validation/validation.go
  pkg/informers/informers.go
  pkg/informers/kube.go
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/merge.go
  pkg/kubelet/controller.go
  pkg/listwatch/namespace_denylist.go
  pkg/namespacelabeler/labeler.go
  pkg/operator/accessor.go
  pkg/operator/argument.go
  pkg/operator/config.go
  pkg/operator/config_reloader.go
  pkg/operator/defaults.go
  pkg/operator/types.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/statefulset.go
  pkg/thanos/collector.go
  pkg/thanos/operator.go
  pkg/webconfig/tls_credentials.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/scrapeconfig_test.go
  test/e2e/thanosruler_test.go
  test/framework/pod.go
Labels: size/L

#6211 Prevent mistakes with testify lib
  .golangci.yml
  pkg/kubelet/controller_test.go
  pkg/operator/config_test.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset_test.go
  pkg/versionutil/cli_test.go
  test/e2e/config_reloader_test.go
  test/e2e/rules_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/M

#6210 Prevent unnecessary type conversions
  .golangci.yml
  pkg/prometheus/promcfg.go
  pkg/thanos/statefulset_test.go
  test/framework/prometheus.go
Labels: size/S

#6179 feat: emit events for invalid configurations
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  bundle.yaml
  cmd/operator/main.go
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
  pkg/alertmanager/operator.go
  pkg/operator/operator.go
  pkg/operator/rules.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/rules.go
  pkg/thanos/operator.go
  pkg/thanos/rules.go
Labels: size/L

#6194 feat: support the operator make use of the config-reloader tls and basic auth with prometheus/alertmanager webConfigFile
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/framework/alertmanager.go
  test/framework/helpers.go
Labels: size/M

#6197 Add UpdateScale and GetScale methods
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheus.go
  pkg/client/versioned/typed/monitoring/v1/prometheus.go
  pkg/client/versioned/typed/monitoring/v1alpha1/fake/fake_prometheusagent.go
  pkg/client/versioned/typed/monitoring/v1alpha1/prometheusagent.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/prometheusagent_test.go
  test/framework/prometheus.go
  test/framework/prometheusagent.go
Labels: size/M

#6222 chore: fix field name to comply with conventions
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
Labels: size/XS

#6223 chore: cut v0.71.0
  CHANGELOG.md
  Documentation/compatibility.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/operator/defaults.go
Labels: size/L

#6221 chore: fix golangci-lint `Files Exists` errors
  .github/workflows/checks.yaml
Labels: size/XS

#6225 chore: refactor logger and eventrecorder creations
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/operator/operator.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/M

#6207 Enable revive
  .golangci.yml
  test/e2e/prometheus_test.go
  test/framework/config_map.go
  test/framework/deployment.go
  test/framework/helpers.go
  test/framework/prometheus.go
Labels: size/M

#6227 chore: setting `golangci-lint` targeted go version
  .github/workflows/checks.yaml
Labels: size/XS

#6180 chore: create new feature and support issue templates
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/support.md
  .github/ISSUE_TEMPLATE/support.yaml
Labels: size/L

#6135 feat(scrapeConfigs): Add sharding to scrapeConfigs
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Already_Sharded.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_Sharded.golden
Labels: size/M

#6233 chore: fix makefile targets
  Makefile
Labels: size/S

#6234 chore: bump to Prometheus v2.49.1
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6239 ADOPTERS: add authzed
  ADOPTERS.md
Labels: size/S

#6243 ruler: add subpath to volumeMounts if specified
  pkg/thanos/statefulset.go
Labels: size/XS

#6215 chore: refactor creation of the TLS assets volume
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/operator/sharded_secret.go
  pkg/operator/sharded_secret_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
Labels: size/L

#6220 feat: add support for DigitalOcean SD in ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/digitaloceansdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD_with_TLSConfig.golden
Labels: size/XL

#6249 ruler: add subpath to volumeMounts if specified (#6243)
  pkg/thanos/statefulset.go
Labels: size/XS

#6251 chore: cut v0.71.1
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6250 chore: bump k8s dependencies to v1.29.1
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/M

#6259 fix: azuresdconfig typo
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/S

#6264 chore: cut v0.71.2
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6268 feat: support added scrape_protocols to Pod/Service monitors
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/podmonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1/probespec.go
  pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/SettingScrapeProtocolsInPodMonitor_NewVersion.golden
  pkg/prometheus/testdata/SettingScrapeProtocolsInPodMonitor_OldVersion.golden
  pkg/prometheus/testdata/SettingScrapeProtocolsInServiceMonitor_NewVersion.golden
  pkg/prometheus/testdata/SettingScrapeProtocolsInServiceMonitor_OldVersion.golden
Labels: size/L
