Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-08, with the labels that each got.

#6795 chore: disable the `generate` job on MacOS
  .github/workflows/checks.yaml
Labels: size/XS

#6790 chore: add test-e2e-feature-gates target
  Makefile
  TESTING.md
Labels: size/XS

#6678 Refactor K8S Service Discovery
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/k8sselectorconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/kubernetessdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Selectors_Unsupported_Version.golden
  test/e2e/main_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/XL

#6728 feat: Add scale subresource to Alertmanger resource
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerstatus.go
  pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  pkg/client/versioned/typed/monitoring/v1/fake/fake_alertmanager.go
  test/e2e/alertmanager_test.go
  test/e2e/main_test.go
  test/e2e/upgradepath_test.go
  test/framework/alertmanager.go
Labels: size/L

#6740 Refactor DNS SD Config
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dnssdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_MXRecord.golden
  test/e2e/scrapeconfig_test.go
Labels: size/L

#6786 replace gokit-log prometheusagent package
  cmd/operator/main.go
  pkg/prometheus/agent/operator.go
Labels: size/L

#6804 bugfix: Fix merge conflict with logger
  pkg/prometheus/agent/operator.go
Labels: size/S

#6793 Rewrite Design.md
  Documentation/design.md
  Documentation/img/alertmanager-config.png
  Documentation/img/config-based-resources.png
  Documentation/img/instance-based-resources.png
  Documentation/img/prometheus-rule.png
Labels: size/L

#6803 chore: avoid version parsing duplication
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
Labels: size/L

#6811 chore: bump to golangci-lint v1.59.1
  .github/workflows/checks.yaml
  scripts/go.mod
  scripts/go.sum
Labels: size/L

#6810 [NONE] upgrading operands
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6809 [NONE] upgrading dependencies
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#6814 feat: Support configuring OAuth2 in ScrapeConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
Labels: size/L

#6782 Replace t.Fatal with require package in tests-e2e
  test/e2e/alertmanager_test.go
  test/e2e/controllerid_test.go
  test/e2e/main_test.go
  test/e2e/prometheusagent_test.go
  test/e2e/scrapeconfig_test.go
  test/e2e/upgradepath_test.go
Labels: size/XL

#6817 chore: re-enable the `generate` job on MacOS
  .github/workflows/checks.yaml
  .mdox.validate.yaml
  Makefile
Labels: size/S

#6735 feat: Support OAuth2 TLSConfig and ProxyConfig settings
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/assets/store.go
  pkg/client/applyconfiguration/monitoring/v1/oauth2.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/pod_monitor_with_oauth2.golden
  pkg/prometheus/testdata/probe_monitor_with_oauth2.golden
  pkg/prometheus/testdata/service_monitor_with_oauth2.golden
Labels: size/XXL

#6818 feat: sync proxy settings in Alertmanager configuration
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/types.go
Labels: size/S

#6819 replace gokitlog in the resource reconciler
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/operator/resource_reconciler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  pkg/thanos/rules.go
Labels: size/L

#6825 replace go kit log in resource selector
  pkg/alertmanager/operator.go
  pkg/operator/accessor.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  test/framework/framework.go
Labels: size/M

#6828 replace go kit log in alertmanager package
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
Labels: size/M

#6827 chore: Update Arthur's affiliation
  MAINTAINERS.md
Labels: size/XS

#6824 [NONE] updating changelog
  CHANGELOG.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
Labels: size/M

#6835 ADOPTERS: Add DACHS IT
  ADOPTERS.md
Labels: size/S

#6834 preparing release-0.76
  CHANGELOG.md
  Documentation/compatibility.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/operator/defaults.go
Labels: size/L

#6842 chore: update controller-runtime version to v1.18.5
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/S

#6832 chore: replace goKitLogger in k8sutil and event handler
  pkg/alertmanager/operator.go
  pkg/k8sutil/secrets.go
  pkg/k8sutil/secrets_test.go
  pkg/operator/event_handler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/M

#6780 feat: support new `otlp` receiver configuration
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/otlpconfig.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/OTLPConfig_Config_empty_attributes.golden
  pkg/prometheus/testdata/OTLPConfig_Config_promote_resource_attributes.golden
Labels: size/L

#6744 Refactor EC2 Service discovery
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ec2sdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SDConfigFilters_Unsupported_Version.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SD_withBasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SD_withProxyConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SD_with_TLSConfig.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EC2SD_with_TLSConfig_Unsupported_Version.golden
  test/e2e/scrapeconfig_test.go
Labels: size/XL

#6849 feat: add MatchFirstNetwork field for DockerSD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dockersdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_MatchFirstNetwork.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_MatchFirstNetwork_OldVersion.golden
Labels: size/L

#6845 fix: allow proxy URL for all Prometheus versions
  pkg/prometheus/promcfg.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_ProxySettingsIncompatiblePrometheusVersion.golden
Labels: size/XS

#6852 Switching the position of Platform and Developer Guide in Website
  Documentation/high-availability.md
  Documentation/operator.md
  Documentation/rbac-crd.md
  Documentation/rbac.md
  Documentation/thanos.md
  Documentation/troubleshooting.md
  Documentation/user-guides/alerting.md
  Documentation/user-guides/getting-started.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/scrapeconfig.md
  Documentation/user-guides/storage.md
  Documentation/user-guides/strategic-merge-patch.md
  Documentation/user-guides/webhook.md
Labels: size/S

#6856 chore: bump to golangci-lint v1.60.1
  .github/workflows/checks.yaml
  pkg/alertmanager/statefulset.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/thanos/statefulset.go
  scripts/go.mod
  scripts/go.sum
Labels: size/L

#6851 feat: Support `OutOfOrderTimeWindow` field for PrometheusAgent
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/PrometheusAgent_TSDB_config_greater_than_or_equal_to_v2.54.0.golden
  pkg/prometheus/testdata/PrometheusAgent_TSDB_config_less_than_v2.53.0.golden
  pkg/prometheus/testdata/PrometheusAgent_no_TSDB_config.golden
Labels: size/L

#6862 replace goKitLogger in WaitForNamedCacheSync
  pkg/alertmanager/operator.go
  pkg/operator/operator.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/S

#6865 fix: fix CHANGELOG format
  CHANGELOG.md
Labels: size/S

#6861 chore: sanitize proxy configuration for Alertmanager
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
Labels: size/L

#6871 chore: Upgrade golang version to 1.23
  .github/env
  go.mod
  scripts/go.mod
Labels: size/S

#6868 replace goKitLogger in alertmanager
  pkg/admission/admission_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
Labels: size/M

#6869 ScrapeConfig: Refactor FileSD
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  test/e2e/scrapeconfig_test.go
Labels: size/M

#6872 chore: simplify kubelet controller constructor
  cmd/operator/main.go
  pkg/kubelet/controller.go
Labels: size/S

#6874 replace goKitLogger in amcfg
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
Labels: size/L

#6881 replace goKitLogger in operators
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/listwatch/listwatch.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/M

#6883 replace goKitLogger in config generator
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/test_utils.go
Labels: size/L

#6888 replace goKitLogger in rules and server
  cmd/admission-webhook/main.go
  cmd/operator/main.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/rules.go
  pkg/server/server.go
  pkg/thanos/operator.go
Labels: size/L

#6890 replace goKitLogger in controller and namespace denylist
  cmd/operator/main.go
  pkg/kubelet/controller.go
  pkg/listwatch/namespace_denylist.go
  pkg/listwatch/namespace_denylist_test.go
Labels: size/M

#6855 Refactor ScrapeConfigSpec
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  test/e2e/scrapeconfig_test.go
Labels: size/XXL

#6787 Allow Prometheus Agent to update, delete, and handle changes to DaemonSet object
  pkg/alertmanager/operator.go
  pkg/k8sutil/k8sutil.go
  pkg/operator/resource_reconciler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  test/e2e/main_test.go
  test/e2e/prometheusagent_test.go
  test/framework/prometheusagent.go
Labels: size/L
