Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-12, with the labels that each got.

#7157 Bump to prometheus v3.0.1
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7161 chore: fix test-e2e-images makefile target
  Makefile
Labels: size/S

#7165 chore: update golangci-lint to v1.62.2
  .github/workflows/checks.yaml
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7158 feat: make prometheus v3.0.1 as default version
  .github/workflows/e2e-prometheus2.yaml
  Documentation/compatibility.md
  cmd/po-docgen/compatibility.go
  pkg/operator/defaults.go
  test/framework/prometheus.go
Labels: size/M

#7162 chore: refactor service creation in Prometheus controllers
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/common.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
Labels: size/L

#7154 Attach Authorization to config via ScrapeClass
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/scrapeclass.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ProbeWithDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/ProbeWithNonDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/ProbeWithNonDefaultScrapeClassUserDefinedAuthz.golden
  pkg/prometheus/testdata/ScrapeConfigWithDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/ScrapeConfigWithNonDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/ScrapeConfigWithNonDefaultScrapeClassUserDefinedAuthz.golden
  pkg/prometheus/testdata/podMonitorObjectWithDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassUserDefinedAuthz.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassAuthz.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassUserDefinedAuthz.golden
Labels: size/L

#7169 Fix make test-e2e-images
  .gitignore
  Makefile
Labels: size/S

#7110 [DOC] add a proposal for zone aware scraping
  Documentation/proposals/202411-zone-aware-sharding.md
Labels: size/L

#7140 [feat] - Add Labels to RuleGroup
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  jsonnet/prometheus-operator/prometheusrules-crd.json
  pkg/apis/monitoring/v1/prometheusrule_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/rulegroup.go
  pkg/operator/rules.go
  pkg/operator/rules_test.go
Labels: size/M

#7177 chore: use ptr.Deref
  pkg/operator/rules.go
Labels: size/XS

#7086 [FEATURE] adding RoleSelector field in ServiceMonitor
  CHANGELOG.md
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/testdata/ServiceMonitorObjectWithEndpointSliceSelectorAndMatchLabelSelector.golden
  pkg/prometheus/testdata/ServiceMonitorObjectWithMatchExpressionSelector.golden
  pkg/prometheus/testdata/ServiceMonitorObjectWithMatchLabelSelector.golden
  pkg/prometheus/testdata/ServiceMonitorObjectWithSelectorAndMatchExpressionSelector.golden
Labels: size/L

#7186 chore: update go dependencies
  Documentation/compatibility.md
  Makefile
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/operator/defaults.go
Labels: size/XL

#7183 feat: Add support for configuring Alertmanager STS persistentVolumeClaimRetentionPolicy
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
Labels: size/M

#7191 feat: add proxy_url to alertmanagerendpoints
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/testdata/AlertmanagerConfigProxyconfig.golden
Labels: size/M

#6004 fix: validate smtp smarthost and smtp from fields
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/CR_with_EmailConfig_Receiver_Conf.golden
  pkg/alertmanager/testdata/CR_with_EmailConfig_Receiver_Global_Defaults_Conf.golden
  test/e2e/alertmanager_test.go
Labels: size/L

#7194 chore: cut v0.79.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#7197 Fix: Remove scrapeFallbackProtocol in Prometheus CommonSpec
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/valid_global_config_with_scrape_fallback_protocol.golden
  pkg/prometheus/testdata/valid_global_config_with_unsupported_scrape_fallback_protocols.golden
Labels: size/M

#7199 CHANGE/BugFix: Rename scrapeFallbackProtocol to fallbackScrapeProtocol
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/podmonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1/probespec.go
  pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/L

#7212 chore: update Kind version to v0.26.0
  .github/env
Labels: size/XS

#7217 [BUGFIX] Fixing pod and service monitor selector validation
  CHANGELOG.md
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/testdata/PodMonitorObjectWithSelectorAndMatchExpressionSelector.golden
Labels: size/M

#7219 chore: cut v0.79.2
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#7218 Merge v0.79.2 back to main
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/testdata/PodMonitorObjectWithSelectorAndMatchExpressionSelector.golden
Labels: size/L

#7098 Add OAuth2 in ScrapeConfig
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_WithOAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_WithOAuth_Unsupported.golden
Labels: size/M

#7170 Fix Broken Links to Ingress Guide and Add Prometheus & Alertmanager Exposure Guide
  Documentation/high-availability.md
  Documentation/operator.md
  Documentation/platform-guide.md
  Documentation/rbac-crd.md
  Documentation/rbac.md
  Documentation/thanos.md
  Documentation/troubleshooting.md
  Documentation/user-guides/exposing-prometheus-and-alertmanager.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/storage.md
  Documentation/user-guides/strategic-merge-patch.md
  Documentation/user-guides/webhook.md
Labels: size/M

#7230 chore: improve documentation of web TLS configuration
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/types_test.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/webtlsconfig.go
  pkg/webconfig/config.go
  pkg/webconfig/config_test.go
  pkg/webconfig/tls_credentials.go
  test/framework/prometheus.go
Labels: size/L

#7231 Refactor LightSailSDConfig
  test/e2e/scrapeconfig_test.go
Labels: size/M

#7233 feat: add PrometheusTopologySharding feature gate
  Documentation/operator.md
  pkg/operator/config.go
  pkg/operator/feature_gates.go
  pkg/prometheus/promcfg.go
Labels: size/M
