Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-04, with the labels that each got.

#6408 feat(xds): Add support eureka service discovery to the ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/eurekasdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD_with_TLSConfig.golden
Labels: size/XL

#6454 Update http_sd description for clarity
  Documentation/user-guides/scrapeconfig.md
Labels: size/XS

#6459 Update kakkoyun's affiliation
  MAINTAINERS.md
Labels: size/XS

#6457 chore: update default prometheus version
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6456 chore: bump go dependencies before release
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#6327 feat(xds): Add Kuma service discovery to the ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/kumasdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD_with_TLSConfig.golden
Labels: size/XL

#6449 Fixed the link in Prometheus Agent page
  Documentation/user-guides/prometheus-agent.md
Labels: size/XS

#6351 Check if controllers' CRDs are provided and manageable by operator
  cmd/operator/main.go
Labels: size/L

#6464 fix: add proxyURL validation for smon,pmon and probe
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/M

#6436 feat: add support for Hetzner SD in ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/hetznersdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_Authorization.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_BasicAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_TLSConfig.golden
Labels: size/XL

#6465 feat(kuma): Add validation for kuma server
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/M

#6359 chore: Add checks for selectors in KubernetesSDConfig (#6177)
  pkg/apis/monitoring/v1/types.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/M

#6425 Allow empty separator in relabel config
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/AdditionalAlertRelabelConfigs.golden
  pkg/prometheus/testdata/AdditionalAlertRelabelConfigs_Expected.golden
  test/e2e/prometheus_test.go
Labels: size/S

#6468 chore: cut v0.73.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#6471 change: define enableFeatures list as a set
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/statefulset.go
  test/framework/prometheus.go
Labels: size/S

#6487 Docs: update TESTING.md
  TESTING.md
Labels: size/S

#6498 chore: cut v0.73.1
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6474 DELETE: removed the po-lint code and doc part
  Documentation/user-guides/linting.md
  Makefile
  README.md
  cmd/po-lint/main.go
  scripts/tooling/Dockerfile
Labels: size/L

#6499 chore: bump to controller-tools v0.14.0
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/informers/externalversions/factory.go
  scripts/go.mod
  scripts/go.sum
Labels: size/XXL

#6451 Fix: Empty replacement is not possible when Action is Replace
  Documentation/api.md
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/namespacelabeler/labeler.go
  pkg/namespacelabeler/labeler_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/GenerateRelabelConfig.golden
  pkg/prometheus/testdata/ProbeSpecConfig_targets_static_config.golden
  test/e2e/prometheus_test.go
Labels: size/L

#6507 fix: ScrapeClass TLSConfig nil pointer exception
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/M

#6506 chore: clean up code in Alertmanager config generation
  pkg/alertmanager/amcfg.go
Labels: size/L

#6522 chore: fix small omission in CRD documentation
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
Labels: size/XS

#6526 fix: ScrapeClass TLSConfig nil pointer exception (#6507)
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/M

#6525 fix: register k8s metrics
  pkg/k8sutil/metrics.go
Labels: size/S

#6497 fix: make automountServiceAccountToken configurable
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/L

#6519 chore: update RELEASE.md with instructions
  RELEASE.md
Labels: size/M

#6527 chore:cut v0.73.2
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6539 chore: update RELEASE.md instructions
  RELEASE.md
Labels: size/XS

#6543 chore: bump to golangci-lint v1.57.2
  .github/workflows/checks.yaml
  scripts/go.mod
  scripts/go.sum
Labels: size/L

#6542 Merge release 0.73 into main
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/k8sutil/metrics.go
Labels: size/L

#6485 feat(xds): Add support nomad service discovery to the ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/nomadsdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD_with_OAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD_with_TLSConfig.golden
Labels: size/XL

#6545 fix generate checks
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
Labels: size/M

#6505 Consider draft PRs electable for staleness
  .github/workflows/stale.yaml
Labels: size/XS

#6551 chore: bump k8s libs to v0.30.0
  Documentation/api.md
  Documentation/compatibility.md
  go.mod
  go.sum
Labels: size/M

#6479 Chore: Change *RelabelConfigs to values instead of Pointers
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/endpoint.go
  pkg/client/applyconfiguration/monitoring/v1/podmetricsendpoint.go
  pkg/client/applyconfiguration/monitoring/v1/probespec.go
  pkg/client/applyconfiguration/monitoring/v1/probetargetingress.go
  pkg/client/applyconfiguration/monitoring/v1/probetargetstaticconfig.go
  pkg/client/applyconfiguration/monitoring/v1/scrapeclass.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/namespacelabeler/labeler.go
  pkg/namespacelabeler/labeler_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  test/e2e/prometheus_test.go
Labels: size/L

#6537 chore: refactor the assets package
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/assets/interface.go
  pkg/assets/store.go
  pkg/assets/store_test.go
  pkg/operator/sharded_secret.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/store.go
  pkg/thanos/operator.go
Labels: size/XL

#6553 doc: fix sample port name used
  Documentation/troubleshooting.md
Labels: size/XS
