Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-10, with the labels that each got.

#6982 chore: add e2e test label for namespaces
  test/framework/namespace.go
Labels: size/XS

#6957 feat: add support for query_offset / global.rule_query_offset (#6956)
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/prometheusrule_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/rulegroup.go
  pkg/operator/rules.go
  pkg/operator/rules_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/valid_global_config_with_rule_query_offset.golden
  pkg/prometheus/testdata/valid_global_config_without_rule_query_offset.golden
Labels: size/L

#6984 chore: add concurrency for workflows
  .github/workflows/checks.yaml
  .github/workflows/e2e-feature-gated.yaml
  .github/workflows/e2e.yaml
  .github/workflows/unit.yaml
Labels: size/S

#6892 FIX: LabelName validation issue
  Documentation/api.md
  pkg/apis/monitoring/v1alpha1/scrapeconfig_test.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/staticconfig.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/M

#3899 Add ability for custom DNSConfig and DNSPolicy
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/dns_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/poddnsconfig.go
  pkg/client/applyconfiguration/monitoring/v1/poddnsconfigoption.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/k8sutil_test.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
Labels: size/XL

#6667 feat: add support for runtime.gogc
  Documentation/api.md
  Documentation/compatibility.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/runtimeconfig.go
  pkg/client/applyconfiguration/utils.go
  pkg/operator/defaults.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/testdata/RuntimeConfig_GoGC25.golden
  pkg/prometheus/testdata/RuntimeConfig_GoGC_Not_Set.golden
Labels: size/L

#6906 feat: support `allow_overlapping_compaction` for prometheus
  Documentation/api.md
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/M

#6634 ScrapeConfig CRD: Proposal For Extending The CRD Surface
  Documentation/proposals/202405-scrapeconfig-graduation.md
Labels: size/L

#6867 ScrapeConfig: Refactor StaticConfig
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  test/e2e/scrapeconfig_test.go
Labels: size/M

#7008 Fix: fix e2e case
  test/e2e/scrapeconfig_test.go
Labels: size/XS

#7012 chore: update controller-tools version to v0.16.4
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7011 chore: add v3.0.0-beta.1 to experimental versions
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7014 chore: add simonpasquier as v0.78 shepherd
  RELEASE.md
Labels: size/XS

#7013 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#7017 Fix issue #7002
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/S

#7015 Fix: fix warning message with make clean generate command
  Makefile
Labels: size/S

#6998 chore: implement DNS options for DaemonSet
  CHANGELOG.md
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/dns_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/k8sutil_test.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/L

#7020 doc: document deduplication config for Mimir/Grafana Cloud
  Documentation/troubleshooting.md
Labels: size/M

#7019 feat: add `nodeName` to kubelet endpoints
  pkg/kubelet/controller.go
  pkg/kubelet/controller_test.go
Labels: size/S

#7021 Dockerfile: drop double quotes around ARG default values
  Dockerfile
  Makefile
  cmd/admission-webhook/Dockerfile
  cmd/prometheus-config-reloader/Dockerfile
Labels: size/S

#7022 doc: update install instructions
  Documentation/installation.md
  README.md
Labels: size/M

#7027 fix: correct HTTP port name for Kubelet
  CHANGELOG.md
  pkg/kubelet/controller.go
Labels: size/XS

#6395 .github/workflow: make execution of e2e and unit tests conditional
  .github/workflows/changed-files.yaml
  .github/workflows/e2e-feature-gated.yaml
  .github/workflows/e2e.yaml
  .github/workflows/unit.yaml
Labels: size/M

#7028 chore: cut 0.77.2
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6796 feat: support add native histogram config
  Documentation/api.md
  Makefile
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/nativehistogramconfig.go
  pkg/client/applyconfiguration/monitoring/v1/podmonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1/probespec.go
  pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/NativeHistogramConfig.golden
  pkg/prometheus/testdata/NativeHistogramConfigWithMissALL.golden
  pkg/prometheus/testdata/NativeHistogramConfigWithMissNativeHistogramMinBucketFactor.golden
Labels: size/L

#7031 Merge release 0.77.2
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/kubelet/controller.go
Labels: size/M

#7030 chore: markdown lint fixes in CONTRIBUTING.md
  .github/workflows/unit.yaml
  CONTRIBUTING.md
Labels: size/M

#6992 fix: address OpenAPI text inconsistency for `prometheus.spec.remoteWrite.sendExemplars`
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
Labels: size/XS

#6781 Proposal for RemoteWrite CRD
  Documentation/proposals/202407-remote-write.md
Labels: size/L

#7033 feat: add support for Remote Write v2.0
  CHANGELOG.md
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/common.go
  pkg/prometheus/common_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/testdata/RemoteWriteConfig_v2.53.0_MessageVersion2.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.54.0_MessageVersion2.golden
  test/e2e/prometheus_test.go
  test/framework/prometheus.go
Labels: size/L

#7041 chore: add prometheus v2.55.0
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7045 chore: update k8s libraries to v0.31.2
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#7044 chore: refactor shared functions in pkg/prometeus
  pkg/prometheus/agent/common.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/common.go
  pkg/prometheus/common_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/server/statefulset.go
  test/framework/context.go
  test/framework/pod.go
Labels: size/L

#7029 enhance: change thanos sidecar promethes.http-client params to prometheus.http-client-file and save config file in secret
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/operator_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/server/thanos_sidecar_config.go
Labels: size/L

#7056 chore: update CoC links
  code-of-conduct.md
Labels: size/XS

#7052 chore: refactor internal code
  Documentation/api.md
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/assets/store.go
  pkg/operator/resource_reconciler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/operator.go
  pkg/prometheus/operator_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
  pkg/prometheus/testdata/RemoteReadConfig_v2.25.0.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.26.0.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.26.0_AuthorizationSafe.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.26.0_FilterExternalLabels.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.26.0_NotFollowRedirects.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.27.1.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.34.0.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.34.0_FilterExternalLabels.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.34.0_NotFilterExternalLabels.golden
  pkg/prometheus/testdata/RemoteReadConfig_v2.43.0_ProxyConfig.golden
  pkg/prometheus/testdata/RemoteWriteConfigAzureADOAuth_v2.47.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfigAzureADOAuth_v2.48.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfigAzureADSDK_v2.51.0.golden
  pkg/prometheus/testdata/RemoteWriteConfigAzureADSDK_v2.52.0.golden
  pkg/prometheus/testdata/RemoteWriteConfig_3.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.10.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.22.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.23.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.23.0_2.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.26.0_2.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.27.1_1.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.30.0_2.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.39.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.43.0_2.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.43.0_ProxyConfig.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.43.0_ProxyConfigWithMutiValues.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.45.0_1.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.49.0.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.50.0.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.53.0_MessageVersion2.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.54.0_MessageVersion2.golden
  pkg/prometheus/testdata/external_label_specified.golden
  pkg/prometheus/testdata/external_label_specified_along_with_reserved_labels.golden
  pkg/prometheus/testdata/global_settings_valid_config_v2.15.2.golden
  pkg/prometheus/testdata/query_log_file.golden
  pkg/prometheus/testdata/valid_global_config_with_keep_dropped_targets.golden
  pkg/prometheus/testdata/valid_global_config_with_label_limits.golden
  pkg/prometheus/testdata/valid_global_config_with_rule_query_offset.golden
  pkg/prometheus/testdata/valid_global_config_with_scrape_protocols.golden
  pkg/prometheus/testdata/valid_global_config_without_rule_query_offset.golden
  pkg/prometheus/testdata/valid_global_limits.golden
  pkg/prometheus/testdata/valid_scrape_timeout_along_with_valid_scrape_interval_specified.golden
  pkg/thanos/operator.go
Labels: size/L

#7060 chore: cut v0.78.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#7058 chore: allow to save e2e diagnostics to disk
  .github/workflows/e2e-feature-gated.yaml
  .github/workflows/e2e-prometheus3.yaml
  .github/workflows/e2e.yaml
  .github/workflows/test-prom-version-upgrade.yaml
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/framework/context.go
  test/framework/pod.go
  test/framework/prometheus.go
Labels: size/L
