Repository prometheus-operator/prometheus-operator, pull requests merged in 2024-09, with the labels that each got.

#6893 chore: bump to prometheus version v2.54.1
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#6894 Fix: `MatchFirstNetwork` dependency on prometheus version v2.54.1
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
Labels: size/XS

#6895 chore: Add [iflytek](https://iflytek.com/)
  ADOPTERS.md
Labels: size/S

#6732 [Feat]: Add Ionos Service Discovery to ScrapeConfig CRD
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/ionossdconfig.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_IonosSD.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_IonosSD_withTLSConfig.golden
  test/e2e/scrapeconfig_test.go
Labels: size/XL

#6898 [NONE] preparing 0.76.1
  CHANGELOG.md
  Documentation/operator.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6904 [NONE] merge request release 0.76
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Selectors.golden
  test/e2e/scrapeconfig_test.go
Labels: size/L

#6907 chore: Upgrade golang version to 1.23 and controller-runtime version to 0.19.0
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/S

#6915 chore: refactor NewConfigGenerator() with functional options
  pkg/prometheus/agent/daemonset_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/M

#6903 chore: reduce e2e test timeouts
  test/e2e/prometheus_test.go
  test/e2e/prometheusagent_test.go
  test/framework/crd.go
  test/framework/prometheusagent.go
Labels: size/M

#6918 doc: add instructions for port forwarding
  .mdox.validate.yaml
  Documentation/troubleshooting.md
Labels: size/S

#6925 Update exporter toolkit to v0.13.0
  cmd/prometheus-config-reloader/main.go
  go.mod
  go.sum
Labels: size/XS

#6927 chore: fix typo in ThanosRuler CRD doc
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/thanos_types.go
Labels: size/XS

#6920 doc: add design doc about status subresource
  Documentation/proposals/202409-status-subresource.md
Labels: size/L

#6928 Add slashpai as release shepherd for v0.77
  RELEASE.md
Labels: size/XS

#6926 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
  Documentation/proposals/template.md
Labels: size/M

#6921 feat: optimize []string annotation
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  test/e2e/scrapeconfig_test.go
Labels: size/L

#6922 supporting new proxy fields into the AlertmanagerConfig CRD for the O…
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/types.go
  pkg/apis/monitoring/v1/types.go
Labels: size/M

#6934 Merge release 0.76
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/types_test.go
  pkg/client/go.mod
Labels: size/L

#6936 fix: avoid BADKEY error in logs
  pkg/alertmanager/operator.go
Labels: size/XS

#6606 feat: added validation for prometheusRule size (#6478)
  pkg/operator/rules.go
  pkg/operator/rules_test.go
  pkg/prometheus/server/rules.go
  pkg/prometheus/server/rules_test.go
  pkg/thanos/rules.go
Labels: size/M

#6358 feat: Support file paths for certificate, key and client CA in web TL…
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/types_test.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/webtlsconfig.go
  pkg/webconfig/config.go
  pkg/webconfig/config_test.go
  pkg/webconfig/testdata/TLS_config_with_client_CA_cert_and_key_files.golden
  pkg/webconfig/tls_credentials.go
Labels: size/L

#6938 chore: simplify owner lookup
  pkg/alertmanager/operator.go
  pkg/operator/resource_reconciler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/operator_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/operator_test.go
  pkg/thanos/operator.go
Labels: size/L

#6882 feat: support EndpointSlice for the kubelet controller
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  bundle.yaml
  cmd/operator/main.go
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
  pkg/alertmanager/operator.go
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/k8sutil_test.go
  pkg/kubelet/controller.go
  pkg/kubelet/controller_test.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/XXL

#6931 fix: validate child routes
  CHANGELOG.md
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/alertmanager/validation/v1alpha1/validation.go
  pkg/alertmanager/validation/v1beta1/validation.go
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
Labels: size/L

#6947 chore: update dependencies before v0.77
  Documentation/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/operator/defaults.go
  scripts/go.mod
  scripts/go.sum
Labels: size/L

#6879 Support PodMonitor for Prometheus Agent in DaemonSet mode
  pkg/prometheus/agent/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/PromAgentDaemonSetPodMonitorConfig.golden
  test/e2e/main_test.go
  test/e2e/prometheusagent_test.go
  test/framework/prometheusagent.go
  test/framework/resources/basic-app-for-daemonset-test.yaml
Labels: size/L

#6940 feat: add experimental Prometheus 3 support
  .github/workflows/e2e-prometheus3.yaml
  .github/workflows/test-prom-version-upgrade.yaml
  Documentation/compatibility.md
  cmd/po-docgen/compatibility.go
  pkg/operator/defaults.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/daemonset_test.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/promcfg.go
  test/framework/prometheus.go
Labels: size/L

#6950 chore: cut 0.77.0
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#6951 chore: update golangci-lint and controller-tools version
  .github/workflows/checks.yaml
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#6953 chore: simplify prometheus server controller
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/L

#6963 chore: add LOG_LEVEL variable to scripts/run-external.sh
  scripts/run-external.sh
Labels: size/XS

#6964 fix: ensure reconciliation on Thanos sts updates
  CHANGELOG.md
  pkg/operator/resource_reconciler.go
  pkg/thanos/operator.go
  pkg/thanos/statefulset.go
Labels: size/M

#6965 fix: fix error message for unsupported versions
  CHANGELOG.md
  pkg/alertmanager/statefulset.go
  pkg/prometheus/promcfg.go
Labels: size/XS

#6967 chore: cut 0.77.1
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#6960 test: improve e2e test troubleshooting
  Makefile
  pkg/prometheus/promcfg.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/framework/context.go
  test/framework/event.go
  test/framework/helpers.go
  test/framework/namespace.go
  test/framework/pod.go
  test/framework/prometheus.go
Labels: size/L

#6959 .github/workflow: Fix prometheus 3 tests
  .github/workflows/e2e-prometheus3.yaml
  test/framework/prometheus.go
Labels: size/S

#6972 Merge release 0.77
  CHANGELOG.md
  Documentation/operator.md
  Documentation/rbac.md
  Documentation/user-guides/prometheus-agent.md
  Documentation/user-guides/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/client/go.mod
  pkg/operator/resource_reconciler.go
  pkg/prometheus/promcfg.go
  pkg/thanos/operator.go
  pkg/thanos/statefulset.go
Labels: size/L

#6958 chore: simplify Prometheus server and agent code
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/test_utils.go
  pkg/prometheus/common.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/L

#6961 build: move build step to Dockerfiles
  Dockerfile
  Makefile
  cmd/admission-webhook/Dockerfile
  cmd/prometheus-config-reloader/Dockerfile
Labels: size/M

#6979 feat: empty string values test cases
  TESTING.md
  test/e2e/scrapeconfig_test.go
Labels: size/M
