Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-05, with the labels that each got.

#7486 Use the AlertmanagerConfig builder outside of the operator repo
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
Labels: size/M

#7500 fix: resolve doc CI failures
  .mdox.validate.yaml
Labels: size/XS

#7498 fix: enable remote-write for Ruler only when set
  CHANGELOG.md
  pkg/thanos/statefulset.go
  test/e2e/prometheus_test.go
  test/e2e/thanosruler_test.go
  test/framework/prometheus.go
  test/framework/thanos_querier.go
Labels: size/L

#7507 Backport release 0.82
  .mdox.validate.yaml
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
  pkg/thanos/statefulset.go
  test/e2e/prometheus_test.go
  test/e2e/thanosruler_test.go
  test/framework/prometheus.go
  test/framework/thanos_querier.go
Labels: size/L

#7487 chore: Update golangci-lint version to v2.1.5
  .github/env
  .github/workflows/checks.yaml
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7501 chore: Update prometheus version to v3.3.1
  Documentation/getting-started/compatibility.md
  go.mod
  go.sum
  pkg/operator/defaults.go
  pkg/operator/rules.go
Labels: size/XS

#7508 chore: update k8s dependencies
  .github/env
  Documentation/getting-started/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#7510 chore: update jsonnet
  scripts/go.mod
  scripts/go.sum
Labels: size/XS

#7513 Cut 0.82.2
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
Labels: size/M

#7515 *: update go.mod files
  go.mod
  pkg/client/go.mod
Labels: size/XS

#7516 fix: Fix parsing `role` field in openstackSDConfigs in ScrapeConfig CRD
  CHANGELOG.md
  pkg/prometheus/promcfg.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigValid.golden
Labels: size/XS

#7505 chore: filepath error
  Documentation/additional-scrape-config.md
Labels: size/XS

#7518 chore: update changelog to correct date
  CHANGELOG.md
Labels: size/XS

#7519 Backport v0.82.2
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/client/go.mod
  pkg/prometheus/promcfg.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigValid.golden
Labels: size/L

#7521 chore: update k8s dependencies to v0.33.0
  Documentation/api-reference/api.md
  Documentation/getting-started/compatibility.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  pkg/k8sutil/k8sutil.go
  pkg/kubelet/controller.go
  pkg/listwatch/namespace_denylist.go
  pkg/operator/operator.go
  test/framework/service.go
Labels: size/L

#7522 chore: update CI k8s version to v1.33.0
  .github/env
Labels: size/XS

#7524 Add myself as volunteer for the next release
  RELEASE.md
Labels: size/XS

#7523 chore: Update controller-tools to v1.18.0
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/informers/externalversions/monitoring/v1/alertmanager.go
  pkg/client/informers/externalversions/monitoring/v1/podmonitor.go
  pkg/client/informers/externalversions/monitoring/v1/probe.go
  pkg/client/informers/externalversions/monitoring/v1/prometheus.go
  pkg/client/informers/externalversions/monitoring/v1/prometheusrule.go
  pkg/client/informers/externalversions/monitoring/v1/servicemonitor.go
  pkg/client/informers/externalversions/monitoring/v1/thanosruler.go
  pkg/client/informers/externalversions/monitoring/v1alpha1/alertmanagerconfig.go
  pkg/client/informers/externalversions/monitoring/v1alpha1/prometheusagent.go
  pkg/client/informers/externalversions/monitoring/v1alpha1/scrapeconfig.go
  pkg/client/informers/externalversions/monitoring/v1beta1/alertmanagerconfig.go
  pkg/client/versioned/fake/clientset_generated.go
  pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  pkg/client/versioned/typed/monitoring/v1alpha1/monitoring_client.go
  pkg/client/versioned/typed/monitoring/v1beta1/monitoring_client.go
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7525 chore: Update golangci-lint to v2.1.6 and adjust configuration
  .github/env
  .golangci.yml
  scripts/go.mod
  scripts/go.sum
Labels: size/S

#7526 chore: Ignore `istio.io`
  .mdox.validate.yaml
Labels: size/XS

#7531 chore: upgrade k8s dependencies to v0.33.1 and kind version to v0.28.0
  .github/env
  Documentation/getting-started/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#7532 chore: bump prometheus version to v3.4.0
  Documentation/getting-started/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7539 feat: Support add NoTranslation mode option in OTLP Config
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/OTLPConfig_Config_translation_strategy_with_notranslation.golden
Labels: size/M

#7537 chore: update logger with slog's discard handler
  pkg/admission/admission_test.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/statefulset_test.go
  pkg/k8sutil/secrets_test.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/namespace_denylist_test.go
  pkg/prometheus/promcfg.go
  pkg/server/server.go
Labels: size/M

#7546 rfac: status-subresource propsal doc to include only workload crds
  Documentation/proposals/202409-status-subresource.md
Labels: size/XS

#7488 e2e: test for all prometheus-operator metrics in e2e
  pkg/prometheus/collector.go
  test/e2e/prometheus_operator_test.go
Labels: size/M

#7551 added feature gate for status subresource for config obj
  Documentation/platform/operator.md
  pkg/operator/config.go
  pkg/operator/feature_gates.go
  pkg/prometheus/server/operator.go
Labels: size/S

#7563 chore: fix NameEscapingSchemeOptions documentation
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
Labels: size/M

#7564 chore: update proposal template
  CONTRIBUTING.md
  Documentation/proposals/template.md
Labels: size/S

#7566 CHORE: update deps before release 0.83
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/M

#7493 Add Duration type helper
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/types_test.go
Labels: size/S
