Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-08, with the labels that each got.

#7615 fix: reconcile workload configurations when a referenced secret/configmap key is updated
  CHANGELOG.md
  Documentation/platform/operator.md
  cmd/operator/main.go
  pkg/alertmanager/operator.go
  pkg/assets/store.go
  pkg/assets/tracker.go
  pkg/assets/tracker_test.go
  pkg/informers/informers.go
  pkg/informers/informers_test.go
  pkg/informers/kube.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/event_handler.go
  pkg/operator/informers.go
  pkg/operator/operator.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
Labels: size/XXL

#7717 feat: added getConfigResources function
  pkg/prometheus/server/operator.go
Labels: size/M

#7762 feat: add configurable sync period for kubelet endpoints controller
  Documentation/platform/operator.md
  cmd/operator/main.go
  pkg/kubelet/controller.go
Labels: size/S

#7766 feat: optimize event handler
  pkg/alertmanager/operator.go
  pkg/operator/event_handler.go
  pkg/operator/informers.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/L

#7774 chore: update description of `minReadySeconds` fields
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/e2e/thanosruler_test.go
Labels: size/L

#7777 chore: cut v0.84.1
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#7776 feat: add workqueue metrics
  pkg/operator/resource_reconciler.go
  test/e2e/main_test.go
  test/e2e/prometheus_operator_test.go
Labels: size/L

#7769 Feat: add user namespaces support for Thanos
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/M

#7763 feat: optimize statefulset informers
  pkg/alertmanager/operator.go
  pkg/operator/factory.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/common.go
  pkg/prometheus/common_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/statefulset.go
  pkg/thanos/operator.go
Labels: size/M

#7787 feat: optimize daemonset informers
  pkg/prometheus/agent/operator.go
Labels: size/S

#7767 smon status update after reconcillation
  pkg/prometheus/agent/operator.go
  pkg/prometheus/operator.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
Labels: size/L

#7782 Merge 0.84.1 into main
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/L

#7816 Chore: Refactor DockerSD
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/dockersdconfig.go
  pkg/prometheus/promcfg_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/L

#7825 chore: remove po-lint from .gitignore
  .gitignore
Labels: size/XS

#7793 add ServiceMonitor status subresource e2e test
  test/e2e/main_test.go
  test/e2e/status_subresource_test.go
  test/framework/service_monitor.go
  test/framework/status.go
Labels: size/L

#7832 chore: remove step commenting on failed runs
  .github/workflows/checks.yaml
Labels: size/M

#7835 Chore: Update test cases for LinodeSD
  test/e2e/scrapeconfig_test.go
Labels: size/L

#7827 Update service monitor status binding only if a change is detected
  pkg/prometheus/operator.go
  pkg/prometheus/operator_test.go
Labels: size/L

#7838 Chore: Update test cases for NomadSD
  test/e2e/scrapeconfig_test.go
Labels: size/L

#7836 Remove invaldBindings from smon status
  pkg/prometheus/operator.go
  pkg/prometheus/server/operator.go
  test/e2e/main_test.go
  test/e2e/status_subresource_test.go
  test/framework/service_monitor.go
  test/framework/status.go
Labels: size/L

#7841 Chore: Update test cases for PuppetDBSD
  test/e2e/scrapeconfig_test.go
Labels: size/L
