Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-01, with the labels that each got.

#7253 chore: bump to prometheus version v3.1.0
  Documentation/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7190 chore: update .golangci.yaml config
  .golangci.yml
Labels: size/XS

#7235 chore: reduce code duplication in agent controller
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  test/e2e/prometheusagent_test.go
  test/framework/prometheusagent.go
Labels: size/L

#7257 [fix] - Scrape Timeout Doc
  Documentation/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
Labels: size/S

#7229 Reorganize Documentation Folder
  Documentation/api-reference/api.md
  Documentation/developer/alerting.md
  Documentation/developer/getting-started.md
  Documentation/developer/scrapeconfig.md
  Documentation/getting-started/compatibility.md
  Documentation/getting-started/design.md
  Documentation/getting-started/installation.md
  Documentation/getting-started/introduction.md
  Documentation/platform/exposing-prometheus-and-alertmanager.md
  Documentation/platform/high-availability.md
  Documentation/platform/operator.md
  Documentation/platform/platform-guide.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac-crd.md
  Documentation/platform/rbac.md
  Documentation/platform/storage.md
  Documentation/platform/strategic-merge-patch.md
  Documentation/platform/thanos.md
  Documentation/platform/troubleshooting.md
  Documentation/platform/webhook.md
  Makefile
  README.md
Labels: size/S

#7259 [fix] - Docs pipeline
  Documentation/proposals/202411-zone-aware-sharding.md
  README.md
Labels: size/S

#7250 chore: Update golangci-lint to v1.63.4
  .github/workflows/actionlint.yml
  .github/workflows/checks.yaml
  .golangci.yml
  go.mod
  pkg/alertmanager/statefulset_test.go
  pkg/operator/config.go
  scripts/go.mod
  scripts/go.sum
  test/e2e/prometheusagent_test.go
  test/framework/framework.go
Labels: size/L

#7240 feat: Support add `KeepIdentifyingResourceAttributes` in OTLPConfig
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/otlpconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/OTLPConfig_Config_keep_identifying_resource_attributes.golden
  pkg/prometheus/testdata/OTLPConfig_Config_keep_identifying_resource_attributes_with_old_version.golden
Labels: size/M

#7268 chore: Bump to controller-runtime version v0.19.4
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/S

#6687 Feat: Add `servicename` field to the Prometheus server and agent CRDs
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/common.go
  pkg/prometheus/common_test.go
  pkg/prometheus/server/operator.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/prometheusagent_test.go
Labels: size/L

#7273 chore: add slashpai as release shepherd for v0.80
  RELEASE.md
Labels: size/XS

#7281 chore: Update alertmanager to v0.28.0
  Documentation/getting-started/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7288 feat: add fallbackScrapeProtocol to ScrapeClass
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  o.txt
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/scrapeclass.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/monitorObjectWithDefaultScrapeClassAndFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/podMonitorObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/probeObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/probeObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/scrapeConfigObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/scrapeConfigObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
  pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
Labels: size/XXL

#7292 Fix: golangci-lint config timeout option
  .golangci.yml
Labels: size/XS

#7296 feat: santize msteamsv2config
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/msteamsv2_config_for_supported_versions.golden
  pkg/alertmanager/types.go
Labels: size/M

#7220 [feat] - Refactor GCESDConfig
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/gcesdconfig.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValidRequiredFields.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValid_all_options.golden
  test/e2e/scrapeconfig_test.go
Labels: size/L

#7295 chore: update go dependencies for release v0.80
  Documentation/getting-started/compatibility.md
  go.mod
  go.sum
  o.txt
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/XXL

#7239 fix: add ProxyConfig and TLSConfig validate in ScalewaySD
  pkg/prometheus/resource_selector.go
Labels: size/XS

#7293 chore: remove `GODEBUG=gotypesalias=0` option
  Documentation/api-reference/api.md
  Makefile
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7215 [feat] - Refactor AzureSD
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/azuresdconfig.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValidWithSubscriptionID.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_ManagedIdentityAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_SDKAuth.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_basic_auth_and_TLS.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_http_config.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_with_oauth2.golden
  test/e2e/scrapeconfig_test.go
Labels: size/XXL

#7305 chore: Fix generate check
  Documentation/api-reference/api.md
Labels: size/XS

#7238 chore: Refactor OVHCloudSDConfig
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/resource_selector_test.go
  test/e2e/scrapeconfig_test.go
Labels: size/L

#6585 Fix: One Alertmanager Config failing blocks all others.
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/alertmanager/validation/validation.go
  pkg/alertmanager/validation/validation_test.go
Labels: size/L

#7308 chore: rename prometheus 2 actions file
  .github/workflows/e2e-prometheus-v2.yaml
Labels: size/XS

#7038 feat: Add support `scrape_failure_log_file` for prometheus and prometheusAgent
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/common.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/prometheus/testdata/PrometheusAgent_no_scrapeFailureLogFile.golden
  pkg/prometheus/testdata/PrometheusAgent_scrapeFailureLogFile_empty_path_v2.55.0.golden
  pkg/prometheus/testdata/PrometheusAgent_scrapeFailureLogFile_greater_than_or_equal_to_v2.55.0.golden
  pkg/prometheus/testdata/PrometheusAgent_scrapeFailureLogFile_less_than_v2.54.0.golden
  pkg/prometheus/testdata/scrape_failure_log_file.golden
  pkg/prometheus/testdata/scrape_failure_log_file_empty_path.golden
  pkg/prometheus/testdata/scrape_failure_log_file_unsupported_version.golden
Labels: size/L
