Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-03, with the labels that each got.

#7373 Add myself for v0.83 release
  RELEASE.md
Labels: size/XS

#7376 Add myself to the list of maintainers
  MAINTAINERS.md
Labels: size/XS

#7392 Add myself to triage team
  MAINTAINERS.md
Labels: size/XS

#7384 feat: support pod spec field "enableServiceLinks" (#7383)
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/daemonset_test.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/agent/statefulset_test.go
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/L

#7394 chore: update Go dependencies
  Documentation/getting-started/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7395 chore: refactor following #7149
  pkg/alertmanager/clustertlsconfig/config.go
  pkg/alertmanager/clustertlsconfig/config_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
Labels: size/M

#7396 chore: cut v0.81.0
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/M

#7409 fix: unblock feature-gates CI
  pkg/operator/feature_gates.go
  test/e2e/denylist_test.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/prometheusagent_test.go
  test/e2e/upgradepath_test.go
  test/framework/cluster_role.go
  test/framework/cluster_role_binding.go
  test/framework/context.go
  test/framework/framework.go
  test/framework/role_binding.go
  test/framework/service_account.go
Labels: size/L

#7402 chore: update Alertmanager to v0.28.1
  Documentation/getting-started/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7407 fix - AM tests
  pkg/alertmanager/amcfg_test.go
Labels: size/S

#7419 chore: bump Kubernetes dependencies
  Documentation/getting-started/compatibility.md
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/S

#7414 fix: render metric_name_validation_scheme in config
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/NameValidationSchemeLegacyWithPrometheusV3.golden
  pkg/prometheus/testdata/NameValidationSchemeUTF8WithPrometheusV3.golden
  pkg/prometheus/testdata/OTLPConfig_Config_translation_strategy_with_suffixes_and_name_validation_scheme.golden
Labels: size/S

#7299 Documentation for Scrape Classes
  Documentation/developer/scrapeclass.md
  example/user-guides/scrapeclass/scrapeclass-example-definition.yaml
  example/user-guides/scrapeclass/scrapeclass-example-podmonitor.yaml
  example/user-guides/scrapeclass/scrapeclass-example-servicemonitor.yaml
Labels: size/L

#7385 fix - change AM feature flag
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
Labels: size/L

#6876 feat:validate proxyURL for alertManagerCfg (#6466)
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1alpha1/validation_test.go
  pkg/apis/monitoring/v1beta1/validation.go
  pkg/apis/monitoring/v1beta1/validation_test.go
Labels: size/L

#7377 Feat: Add `Retain` field to the Prometheus CRD
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/retainconfig.go
  pkg/client/applyconfiguration/monitoring/v1/shardretentionpolicy.go
  pkg/client/applyconfiguration/utils.go
  test/e2e/prometheus_test.go
Labels: size/M

#7430 chore: Upgrade golangci-lint to v2 and golangci-lint-action to v7.0.0
  .github/workflows/checks.yaml
  .golangci.yml
  cmd/admission-webhook/main.go
  pkg/alertmanager/operator.go
  pkg/assets/tls.go
  pkg/k8sutil/k8sutil.go
  pkg/kubelet/controller.go
  pkg/listwatch/namespace_denylist.go
  pkg/operator/rules.go
  pkg/operator/statefulset_reporter.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/store.go
  pkg/thanos/operator.go
  scripts/go.mod
  scripts/go.sum
  scripts/tools.go
  test/framework/admission_webhooks.go
  test/framework/context.go
  test/framework/crd.go
  test/framework/prometheus.go
  test/framework/prometheusagent.go
  test/framework/service.go
Labels: size/L
