Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-07, with the labels that each got.

#7656 chore: bump default prometheus version to v3.4.2
  Documentation/getting-started/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7670 feat: add proxyconfig for apiserverConfig
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/apiserverconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/store.go
Labels: size/L

#7667 feat: global always_scrape_classic_histograms
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeClassicHistogramsFalseProperPromVersion.golden
  pkg/prometheus/testdata/ScrapeClassicHistogramsTrueProperPromVersion.golden
  pkg/prometheus/testdata/ScrapeClassicHistogramsTrueWrongPromVersion.golden
Labels: size/L

#7617 shouldUpdate to check if the resource should updated if the finalizer is present
  pkg/k8sutil/k8sutil.go
  pkg/operator/resource_reconciler.go
Labels: size/XS

#7675 feat: add label_selector to HetznerSDConfig
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/hetznersdconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSDLabelSelector.golden
  pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSDNoLabelSelector.golden
Labels: size/L

#7604 feat: Add alertmanagerConfigMatcherStrategy "OnNamespaceExceptForAlertmanagerNamespace"
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/testdata/skeleton_base_diff_namespace_simple_CR_with_namespaceMatcher_disabled_other_namespaces.golden
  pkg/alertmanager/testdata/skeleton_base_same_namespace_simple_CR_with_namespaceMatcher_disabled_other_namespaces.golden
  pkg/apis/monitoring/v1/alertmanager_types.go
Labels: size/L

#7680 Fix link for Materials Page
  Documentation/materials.md
Labels: size/XS

#7661 feat: add ConfigurationUnmanaged reason
  CHANGELOG.md
  pkg/prometheus/server/operator.go
Labels: size/M

#7616 go generic support in syncFinalizer function
  pkg/operator/finalizer.go
  pkg/prometheus/server/operator.go
Labels: size/L

#7654 Feat: Add VictorOps in Global Config
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/valid_global_config_with_VictorOps.golden
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerglobalconfig.go
  pkg/client/applyconfiguration/monitoring/v1/globalvictoropsconfig.go
  pkg/client/applyconfiguration/utils.go
Labels: size/L

#7695 chore: Update golangci-lint version to v2.2.1
  .github/env
  .golangci.yml
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7694 Chore: Update PR template to include fixes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#7722 chore: update prometheus version to 3.5
  Documentation/getting-started/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7735 chore: Update golangci-lint version to v2.2.2
  .github/env
  scripts/go.mod
  scripts/go.sum
Labels: size/S

#7737 chore: Update golangci-lint version to v2.3.0
  .github/env
  Makefile
  scripts/go.mod
  scripts/go.sum
Labels: size/M

#7738 fix typos
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/operator_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/operator/rules.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/common_test.go
  pkg/prometheus/resource_selector_test.go
  test/e2e/prometheus_test.go
Labels: size/M

#7743 fix: unnecessary type object
  pkg/prometheus/resource_selector.go
Labels: size/XS

#7747 Fix overlapping compaction argument
  CHANGELOG.md
  pkg/prometheus/server/statefulset.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/XS

#7558 feat: high cpu troubleshooting
  Documentation/platform/troubleshooting.md
Labels: size/S

#7669 feat: New OTLP attributes configs
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/otlpconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/OTLPConfig_Config_ignore_resource_attributes_and_promote_all_resource_attributes.golden
  pkg/prometheus/testdata/OTLPConfig_Config_ignore_resource_attributes_wrong_prom.golden
  pkg/prometheus/testdata/OTLPConfig_Config_promote_all_resource_attributes.golden
  pkg/prometheus/testdata/OTLPConfig_Config_promote_all_resource_attributes_wrong_prom.golden
Labels: size/L

#7750 feat: add `ruleGracePeriod` options for thanos CRD
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/L

#7729 add `ScrapeConfigSelector` CEL prohibitions for PrometheusAgent DaemonSet mode
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
  test/e2e/prometheusagent_test.go
Labels: size/M

#7749 fix: log only valid resources
  CHANGELOG.md
  pkg/prometheus/resource_selector.go
Labels: size/S

#7718 change ResourcesSelection from slice to map
  pkg/prometheus/resource_selector.go
Labels: size/S

#7754 feat: add support for thanos rule `--enable-feature=promql-experimental-functions`
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: size/L

#7759 fix: validatingwebhook
  test/framework/resources/prometheus-operator-validatingwebhook.yaml
Labels: size/XS
