Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-04, with the labels that each got.

#7338 chore: Upgrade Go version to v1.24
  .github/env
  Dockerfile
  cmd/admission-webhook/Dockerfile
  cmd/prometheus-config-reloader/Dockerfile
  go.mod
  pkg/apis/monitoring/go.mod
  pkg/client/go.mod
  scripts/go.mod
Labels: size/S

#7435 chore: bump Prometheus dependencies
  go.mod
  go.sum
  pkg/operator/rules.go
Labels: size/S

#7310 feat: Add Timeout Config for Webhook Receiver
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/CR_with_WebhookConfig_with_Timeout_Setup.golden
  pkg/alertmanager/testdata/CR_with_WebhookConfig_with_Timeout_Setup_Older_Version.golden
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/webhookconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/webhookconfig.go
Labels: size/L

#7441 chore: update Thanos to v0.38.0
  Documentation/getting-started/compatibility.md
  example/thanos/prometheus.yaml
  example/thanos/query-deployment.yaml
  example/thanos/thanos-ruler.yaml
  jsonnet/thanos/config.libsonnet
  pkg/operator/defaults.go
  test/e2e/prometheus_test.go
Labels: size/S

#7442 chore: fix topology sharding flag in ConfigGenerator
  pkg/prometheus/promcfg.go
Labels: size/M

#7443 feat: add `maxSamplesPerSend` field to RW metadata config
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/metadataconfig.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/testdata/RemoteWriteConfig_v2.28.0_MaxSamplesPerSendMetadataConfig.golden
  pkg/prometheus/testdata/RemoteWriteConfig_v2.29.0_MaxSamplesPerSendMetadataConfig.golden
Labels: size/M

#7160 feat: added doc for deploying in restricted ns #6361
  Documentation/platform/strategic-merge-patch.md
Labels: size/L

#7449 chore: add slashpai as release shepherd 0.82
  RELEASE.md
Labels: size/XS

#7444 feat: add remote-write support for ThanosRuler
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/store.go
  pkg/thanos/operator.go
  pkg/thanos/operator_test.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
  pkg/thanos/testdata/default_remote_write_config.golden
  pkg/thanos/testdata/empty_remote_write_config.golden
  pkg/thanos/testdata/v0.24.0_remote_write_config.golden
  test/e2e/main_test.go
  test/e2e/thanosruler_test.go
Labels: size/XXL

#7455 test: fix testThanosRulerStateless
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/thanosruler_test.go
  test/framework/prometheus.go
Labels: size/L

#7439 feat: add `terminationGracePeriodSeconds` field
  CHANGELOG.md
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  pkg/prometheus/agent/daemonset.go
  pkg/prometheus/agent/statefulset.go
  pkg/prometheus/common.go
  pkg/prometheus/server/statefulset.go
  pkg/thanos/statefulset.go
  test/e2e/prometheus_test.go
Labels: size/L

#7457 promcfg: Remove web console arguments if prometheus version >= 3
  pkg/prometheus/promcfg.go
  pkg/prometheus/server/statefulset_test.go
Labels: size/M

#7460 Allow socks5 proxy URLs
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/apis/monitoring/v1/types.go
Labels: size/L

#7462 chore: bump go dependencies before release 0.82
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
  test/framework/helpers.go
Labels: size/M

#7461 docs: Add documentation on how to use the controller-id flag to prevent shared ownership of objects
  Documentation/platform/troubleshooting.md
Labels: size/S

#7307 feat: Add new discord message fields
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/Discord_avatarURL_add_in_supported_versions_config.golden
  pkg/alertmanager/testdata/Discord_avatarURL_dropped_in_unsupported_versions_config.golden
  pkg/alertmanager/testdata/Discord_content_add_in_supported_versions_config.golden
  pkg/alertmanager/testdata/Discord_content_dropped_in_unsupported_versions_config.golden
  pkg/alertmanager/testdata/Discord_username_add_in_supported_versions_config.golden
  pkg/alertmanager/testdata/Discord_username_dropped_in_unsupported_versions_config.golden
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/discordconfig.go
  pkg/client/applyconfiguration/monitoring/v1beta1/discordconfig.go
Labels: size/L

#7464 feat: Add MSTeamsV2config receiver to CRDs
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/testdata/CR_with_MSTeamsV2_Receiver.golden
  pkg/alertmanager/testdata/CR_with_MSTeamsV2_Receiver_Partial_Conf.golden
  pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  pkg/apis/monitoring/v1beta1/conversion_from.go
  pkg/apis/monitoring/v1beta1/conversion_to.go
  pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/msteamsv2config.go
  pkg/client/applyconfiguration/monitoring/v1alpha1/receiver.go
  pkg/client/applyconfiguration/monitoring/v1beta1/msteamsv2config.go
  pkg/client/applyconfiguration/monitoring/v1beta1/receiver.go
  pkg/client/applyconfiguration/utils.go
Labels: size/XXL

#7469 chore: cut v0.82.0
  CHANGELOG.md
  Documentation/platform/operator.md
  Documentation/platform/prometheus-agent.md
  Documentation/platform/rbac.md
  Documentation/platform/webhook.md
  VERSION
  bundle.yaml
  example/admission-webhook/deployment.yaml
  example/admission-webhook/pod-disruption-budget.yaml
  example/admission-webhook/service-account.yaml
  example/admission-webhook/service-monitor.yaml
  example/admission-webhook/service.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  go.mod
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  pkg/client/go.mod
Labels: size/L

#7397 chore: Add myself to triage team
  MAINTAINERS.md
Labels: size/XS

#7471 docs: Document the operators ability to publish kubernetes events for rejected resources
  Documentation/platform/troubleshooting.md
Labels: size/S

#7474 chore: predefine slice capacity to avoid extra allocations
  pkg/prometheus/server/rules.go
  pkg/thanos/rules.go
Labels: size/S

#7475 chore: Update prometheus version to v3.3.0
  Documentation/getting-started/compatibility.md
  pkg/operator/defaults.go
Labels: size/XS

#7476 chore: Update controller-tools version to v0.17.3
  bundle.yaml
  example/alertmanager-crd-conversion/patch.json
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
  jsonnet/prometheus-operator/alertmanagers-crd.json
  jsonnet/prometheus-operator/podmonitors-crd.json
  jsonnet/prometheus-operator/probes-crd.json
  jsonnet/prometheus-operator/prometheusagents-crd.json
  jsonnet/prometheus-operator/prometheuses-crd.json
  jsonnet/prometheus-operator/prometheusrules-crd.json
  jsonnet/prometheus-operator/scrapeconfigs-crd.json
  jsonnet/prometheus-operator/servicemonitors-crd.json
  jsonnet/prometheus-operator/thanosrulers-crd.json
  scripts/go.mod
  scripts/go.sum
Labels: size/S

#7483 chore: optimize redefines-builtin-id lint
  .golangci.yml
  pkg/k8sutil/k8sutil.go
Labels: size/S

#7478 feat: Add silences limits for alertmanager
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerlimitsspec.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  pkg/client/applyconfiguration/utils.go
Labels: size/L

#7490 doc: Fix dead link
  Documentation/user-guides/monitoring-kubernetes-ingress.md
Labels: size/L
