Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-10, with the labels that each got.

#7942 fix: \"prometheus\" not found log message, after deletion of prometheus, when status flog is enabled
  pkg/operator/finalizer.go
  pkg/prometheus/server/operator.go
Labels: size/XS

#7969 ScrapeConfig Status Subresource Removal from prometheus
  pkg/prometheus/server/operator.go
  test/e2e/main_test.go
  test/e2e/status_subresource_test.go
Labels: size/L

#7973 chore: add myself for v0.87 release
  RELEASE.md
Labels: size/XS

#7978 Add Myself to Triage team
  MAINTAINERS.md
Labels: size/XS

#7988 chore: bump dependencies before release v0.86.0
  go.mod
  go.sum
  pkg/apis/monitoring/go.mod
  pkg/apis/monitoring/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: size/L

#7989 chore: refactor rule management
  pkg/operator/operator.go
  pkg/operator/resource_reconciler.go
  pkg/operator/rules.go
  pkg/operator/rules_test.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/rules.go
  pkg/prometheus/server/rules_test.go
  pkg/thanos/rules.go
Labels: size/XL
