Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-09, with the labels that each got.

#7852 chore: add e2e test for lazy status updates
  pkg/prometheus/operator.go
  pkg/prometheus/operator_test.go
  test/e2e/status_subresource_test.go
  test/framework/status.go
Labels: size/L

#7868 chore: Update golangci-linter to v2.4.0
  .custom-gcl.yaml
Labels: size/XS

#7869 Enable jsontags linter
  .github/workflows/checks.yaml
  .golangci-kal.yml
  CONTRIBUTING.md
  Documentation/api-reference/api.md
  Makefile
  pkg/apis/monitoring/v1/probe_types.go
  pkg/apis/monitoring/v1/prometheus_types.go
  pkg/apis/monitoring/v1/prometheusrule_types.go
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
Labels: size/L

#7888 chore: use JSON patches for status updates
  pkg/prometheus/operator.go
  pkg/prometheus/server/operator.go
Labels: size/L

#7896 Config Status Subresource finalizer in prometheusAgent
  pkg/prometheus/agent/operator.go
  test/e2e/main_test.go
  test/e2e/status_subresource_test.go
Labels: size/M

#7930 test: collect all custom resources on failed test
  test/framework/context.go
Labels: size/L

#7932 chore: simplify ConfigResourceSyncer methods
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/servicemonitor_types.go
  pkg/prometheus/config_resource.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/server/operator.go
Labels: size/M

#7938 chore: collect Kubernetes resources on failed test
  test/framework/context.go
Labels: size/L

#7904 fix(config-reloader): use distinct port name for init container to av…
  pkg/operator/config_reloader.go
Labels: size/XS

#7867 chore: change the `record` api to the new `events` api
  pkg/alertmanager/operator.go
  pkg/operator/operator.go
  pkg/operator/rules.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
Labels: size/M

#7953 chore: inject related object into all events
  pkg/alertmanager/operator.go
  pkg/alertmanager/operator_test.go
  pkg/operator/operator.go
  pkg/operator/rules.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
  pkg/prometheus/server/operator.go
  pkg/prometheus/server/rules.go
  pkg/thanos/operator.go
  pkg/thanos/rules.go
Labels: size/L
