Repository prometheus-operator/prometheus-operator, pull requests merged in 2025-06, with the labels that each got.

#7577 Reusable e2e workflow added
  .github/actions/setup-e2e/action.yaml
  .github/workflows/e2e-feature-gated.yaml
  .github/workflows/e2e-prometheus-v2.yaml
  .github/workflows/e2e.yaml
Labels: size/L

#7596 Ability to update asset store from package consumers
  pkg/assets/store.go
  pkg/assets/store_test.go
Labels: size/M

#7605 chore: Update tools version
  scripts/go.mod
  scripts/go.sum
Labels: size/XS

#7584 finalizer added to workload resources if statusFOrConfigRes flag is enabled
  pkg/alertmanager/operator.go
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/k8sutil_test.go
  pkg/operator/resource_reconciler.go
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
  pkg/thanos/operator.go
  test/e2e/main_test.go
  test/e2e/status_subresource_test.go
Labels: size/L

#7598 Ability to add, get and delete objects from asset store from package consumers
  pkg/assets/store.go
  pkg/assets/store_test.go
Labels: size/L

#7609 updated storage docs to include hostPath volumes
  Documentation/platform/storage.md
Labels: size/M

#7613 chore: add key attribute to ResourceSelector logs
  pkg/prometheus/agent/operator.go
  pkg/prometheus/server/operator.go
Labels: size/S

#7621 ci: decrease kubelet sync frequency
  test/e2e/kind-conf.yaml
Labels: size/S

#7612 chore: refactor ResourceSelector
  pkg/prometheus/resource_selector.go
Labels: size/XL

#7595 feat: added e2e tests for invalid shards and PVCRetentionClaim policy specs in PrometheusAgents DaemonSet deployment model
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  jsonnet/prometheus-operator/prometheusagents-crd.json
  pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
  test/e2e/prometheusagent_test.go
Labels: size/M

#7631 Feat: Add Telegram in Global Config
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/valid_global_config_with_Telegram_API_URL.golden
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerglobalconfig.go
  pkg/client/applyconfiguration/monitoring/v1/globaltelegramconfig.go
  pkg/client/applyconfiguration/utils.go
Labels: size/L

#7626 Feat: Add Jira in Global Config
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  jsonnet/prometheus-operator/alertmanagers-crd.json
  pkg/alertmanager/amcfg.go
  pkg/alertmanager/amcfg_test.go
  pkg/alertmanager/testdata/valid_global_config_with_Jira_API_URL.golden
  pkg/alertmanager/types.go
  pkg/apis/monitoring/v1/alertmanager_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/alertmanagerglobalconfig.go
  pkg/client/applyconfiguration/monitoring/v1/globaljiraconfig.go
  pkg/client/applyconfiguration/utils.go
Labels: size/L

#7652 Support ProxyConfig fields for PodMonitor
  Documentation/api-reference/api.md
  bundle.yaml
  example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  jsonnet/prometheus-operator/podmonitors-crd.json
  pkg/apis/monitoring/v1/podmonitor_types.go
  pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/monitoring/v1/podmetricsendpoint.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/resource_selector.go
  pkg/prometheus/resource_selector_test.go
Labels: size/L
